#!/usr/bin/env python3
"""Generate `data` for SigLIP projection/MLP bias-add.

Every linear in the SmolVLA vision tower carries a bias (confirmed from the weight
manifest: self_attn.{q,k,v,out}_proj.bias, mlp.fc1.bias, mlp.fc2.bias, all [768] or
[3072]) -- unlike the Llama-class text projections, which have none. This is the
bias-add epilogue on a GEMM move-out:

  out[t, c] = proj[t, c] + bias[c]      (bias broadcast over the token rows)

Same op class as the DeepSeek QKV bias; here at the vision
out-proj width N = 768, M = 32 tokens. The projection feeding it is a genuine fp8
MX-Gemmini move-out (stored bf16); the bias is precision-light fp32. Kept as fp32
here for a clean numpy golden of the add + broadcast (the arithmetic under test).

Emit helpers come from the shared golden module (lib/golden).
"""
import pathlib
import sys

import numpy as np

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parents[2] / "lib" / "golden"))
import golden as G

HERE = pathlib.Path(__file__).resolve().parent

N = 768            # vision out_proj / q/k/v width (fc2 also 768; fc1 would be 3072)
M = 32             # token tile


def main():
    rng = np.random.default_rng(0xB1A5C0)
    proj = (rng.standard_normal((M, N))).astype(np.float32)
    bias = (0.3 * rng.standard_normal(N)).astype(np.float32)
    out = (proj + bias[None, :]).astype(np.float32)

    with open(HERE / "data", "w") as f:
        f.write("// @generated by gen_data.py -- SigLIP vision projection/MLP bias-add\n")
        f.write("#include <stdint.h>\n")
        f.write(f"#define BA_M {M}\n#define BA_N {N}\n#define VERIFY_COUNT {M * N}\n")
        G.emit_f32(f, "proj_raw", proj, dims="[BA_M * BA_N]", ncol=8)
        G.emit_f32(f, "bias_raw", bias, dims="[BA_N]", ncol=8)
        G.emit_f32(f, "out_raw", np.zeros(M * N, dtype=np.float32), dims="[BA_M * BA_N]", ncol=8)
        G.emit_f32(f, "gold_raw", out, dims="[BA_M * BA_N]", ncol=8)
    print(f"wrote data M={M} N={N}")


if __name__ == "__main__":
    main()
