// Auto-composed by radiance_muon._bundle_kernel from CompGen's
// bundle/generated_kernels/* + payload.mlir + execution_plan.yaml +
// golden_inputs.pt + golden_outputs.pt.
//
// Per-region compute callbacks come from the
// radiance_muon_elementwise provider verbatim. The pack contributes
// data baking, dispatch sequencing, and verification.
#include <mu_intrinsics.h>
#include <mu_schedule.h>
#include <stdint.h>

#define N 4

// ========== region matmul_0 (op=linalg.matmul) ==========
// Auto-generated by RadianceMuonMatmulProvider.
// region_id = matmul_0
// op_family = matmul
// M         = 2
// K         = 2
// N         = 2
//
// Compute-only emit. The pack's composer wraps this with includes,
// data arrays (M*K + K*N flat float32 init), an MxN output buffer,
// dispatch sequencing, and verification against the model's golden.

struct compgen_region_matmul_0_args {
  __global float* A;   // M*K row-major
  __global float* B;   // K*N row-major
  __global float* C;   // M*N row-major
};

static inline void compgen_region_matmul_0_compute(
    void* arg, uint32_t tid, uint32_t /*nthreads*/, uint32_t /*blk*/) {
  if (tid != 0) return;
  auto* a = reinterpret_cast<compgen_region_matmul_0_args*>(arg);
  for (uint32_t m = 0; m < 2; ++m) {
    for (uint32_t n = 0; n < 2; ++n) {
      float acc = 0.0f;
      for (uint32_t k = 0; k < 2; ++k) {
        acc += a->A[m * 2 + k] * a->B[k * 2 + n];
      }
      a->C[m * 2 + n] = acc;
    }
  }
}

struct compgen_pack_matmul_0_args {
  __global float* A;
  __global float* B;
  __global float* C;
};

static void compgen_pack_matmul_0_callback(
    void* arg, uint32_t tid, uint32_t nthreads, uint32_t blk) {
  auto* a = reinterpret_cast<compgen_pack_matmul_0_args*>(arg);
  compgen_region_matmul_0_args inner = { a->A, a->B, a->C };
  compgen_region_matmul_0_compute(&inner, tid, nthreads, blk);
}

__global float A_data_0[4] = { 0x1.8e11060000000p-3f, -0x1.d0cee80000000p+0f, -0x1.dab5b60000000p+0f, -0x1.1ce8de0000000p+0f };
__global float A_data_1[4] = { -0x1.2635f80000000p-1f, 0x1.4c18440000000p-3f, -0x1.4f6dda0000000p+0f, 0x1.9b38380000000p-1f };
__global float compgen_host_out_buf[N] = { -0x1.dbf59cp+126f, -0x1.dbf59cp+126f, -0x1.dbf59cp+126f, -0x1.dbf59cp+126f };

int main() {
  {
    compgen_pack_matmul_0_args a = { A_data_0, A_data_1, compgen_host_out_buf };
    mu_schedule(compgen_pack_matmul_0_callback, &a, 1);
  }
  return 0;
}
