#!/usr/bin/env python3
"""Generate `data` for SigLIP vision LayerNorm.

The SmolVLA vision tower (SmolVLM2-500M SigLIP encoder) normalizes with
**LayerNorm** (mean-subtract + variance + gamma scale + beta bias), NOT RMSNorm.
Confirmed from the real weight manifest (vision_model.encoder.layers.N.layer_norm1/
layer_norm2 + post_layernorm each carry .weight AND .bias) and the captured op graph
(575 aten.native_layer_norm, eps = 1.000000e-06).

  mean[t]  = (1/D) * sum_j x[t,j]
  var[t]   = (1/D) * sum_j (x[t,j] - mean[t])^2         (biased, torch LayerNorm)
  xhat     = (x[t,j] - mean[t]) / sqrt(var[t] + eps)
  out[t,j] = xhat * gamma[j] + beta[j]

This is the genuinely-new op vs the RMSNorm-complete kernel set: RMSNorm has no
mean-subtraction and no beta. Everything is fp32 (the graph's orig_dtype for the
norm region is float32; norms are precision-light). Real vision hidden D = 768;
M = 32 tokens is a representative tile of the 1024 (=32x32) patch tokens.

Golden = numpy fp32 with the identical arithmetic; verify is FP-tolerance (absorbs
rsqrt / reassociation rounding, still catches a missing mean-sub or beta).

The device kernel computes the stats in ONE pass (Sx = sum x, Sxx = sum x^2 ->
mean = Sx/D, var = Sxx/D - mean^2), which is the same value as the two-pass form
up to fp32 reassociation (values are O(1), mild cancellation, well within tol).

Emit helpers come from the shared golden module (lib/golden).
"""
import pathlib
import sys

import numpy as np

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parents[2] / "lib" / "golden"))
import golden as G

HERE = pathlib.Path(__file__).resolve().parent

D = 768           # SigLIP vision hidden size
M = 32            # token tile (of 1024 patch tokens)
EPS = 1.0e-6       # SiglipVisionConfig layer_norm_eps


def main():
    rng = np.random.default_rng(0x51611)
    # activations feeding a vision LayerNorm: mix scale + nonzero mean so the
    # mean-subtraction actually matters (a missing mean-sub must diverge).
    x = (2.0 * rng.standard_normal((M, D)) + 0.7).astype(np.float32)
    gamma = (1.0 + 0.1 * rng.standard_normal(D)).astype(np.float32)
    beta = (0.2 * rng.standard_normal(D)).astype(np.float32)

    mean = x.mean(axis=1, keepdims=True)
    var = ((x - mean) ** 2).mean(axis=1, keepdims=True)      # biased
    xhat = (x - mean) / np.sqrt(var + EPS)
    out = (xhat * gamma[None, :] + beta[None, :]).astype(np.float32)

    with open(HERE / "data", "w") as f:
        f.write("// @generated by gen_data.py -- SigLIP vision LayerNorm (mean-sub + gamma + beta)\n")
        f.write("#include <stdint.h>\n")
        f.write(f"#define LN_M {M}\n#define LN_D {D}\n")
        f.write(f"#define VERIFY_COUNT {M * D}\n")
        f.write(f"static const float LN_EPS = {EPS:.9e}f;\n")
        G.emit_f32(f, "x_raw", x, dims="[LN_M * LN_D]", ncol=8)
        G.emit_f32(f, "gamma_raw", gamma, dims="[LN_D]", ncol=8)
        G.emit_f32(f, "beta_raw", beta, dims="[LN_D]", ncol=8)
        G.emit_f32(f, "out_raw", np.zeros(M * D, dtype=np.float32), dims="[LN_M * LN_D]", ncol=8)
        G.emit_f32(f, "gold_raw", out, dims="[LN_M * LN_D]", ncol=8)

    # sanity: a mean-sub-free (RMSNorm-style) result must differ substantially
    rms = (x / np.sqrt((x ** 2).mean(axis=1, keepdims=True) + EPS)) * gamma[None, :] + beta[None, :]
    frac = float((np.abs(rms - out) > 1e-2 * np.abs(out) + 1e-3).mean())
    print(f"wrote data M={M} D={D} eps={EPS}; RMSNorm-vs-LayerNorm differs on {frac*100:.1f}% of elems")


if __name__ == "__main__":
    main()
