// Auto-generated by RadianceMuonElementwiseProvider for op_family=mul, N=4.
// Compute kernel + on-GPU bit-comparison against expected output.
// Concrete A/B/EXP data are filled in by the pack from CompGen's
// golden tensors at build time.
#include <mu_intrinsics.h>
#include <mu_schedule.h>
#include <stdint.h>

#define N 4

struct Args {
  __global float* A;
  __global float* B;
  __global float* C;
  __global float* EXP;
  __global volatile uint32_t* mismatch;
};
static inline void compute_kernel(
    void* arg, uint32_t tid, uint32_t nthreads, uint32_t /*blk*/) {
  auto* a = reinterpret_cast<Args*>(arg);
  if (tid == 0) {
    for (uint32_t i = 0; i < N; ++i) {
      a->C[i] = a->A[i] * a->B[i];
    }
    uint32_t bad = 0;
    for (uint32_t i = 0; i < N; ++i) {
      uint32_t got = __builtin_bit_cast(uint32_t, a->C[i]);
      uint32_t exp = __builtin_bit_cast(uint32_t, a->EXP[i]);
      if (got != exp) { bad = 1; break; }
    }
    if (bad) {
      *a->mismatch = 0xDEADBEEFu;
      for (;;) { /* never go idle — sim cycle-budget will fire */ }
    }
  }
}
__global float A_raw[N]   = { 0x1.74ef980000000p+0f, 0x1.f3084e0000000p-2f, 0x1.7030b60000000p-6f, -0x1.6dd6540000000p-5f };
__global float B_raw[N]   = { 0x1.50d0700000000p-2f, -0x1.5856840000000p-1f, 0x1.f0a66e0000000p-8f, -0x1.09d2560000000p-5f };
__global float C_raw[N]   = { 0.0f, 0.0f, 0.0f, 0.0f };
__global float EXP_raw[N] = { 0x1.eaaa1e0000000p-2f, -0x1.4f9de80000000p-2f, 0x1.6526e00000000p-13f, 0x1.7bdf720000000p-10f };
__global volatile uint32_t mismatch_flag = 0u;

static Args args = { nullptr, nullptr, nullptr, nullptr, nullptr };

int main() {
  args.A = A_raw;
  args.B = B_raw;
  args.C = C_raw;
  args.EXP = EXP_raw;
  args.mismatch = &mismatch_flag;
  mu_schedule(compute_kernel, &args, 1);
  return 0;
}
