#!/usr/bin/env python3
"""Generate `data` for the Gemma-2 scaled embedding gather.

  out[t, :] = TABLE[ids[t], :] * sqrt(D)          scale = sqrt(2304) = 48.0 (exact)

fp32, TT=16 tokens, DD=2304 (real Gemma-2-2b hidden), V=96 vocab rows. Gather + exact
power-of-two scale, so the golden is bit-exact; the kernel verifies with a tight FP
tolerance. Emit helpers come from the shared golden module (lib/golden).
"""
import math
import pathlib
import sys

import numpy as np

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parents[2] / "lib" / "golden"))
import golden as G

HERE = pathlib.Path(__file__).resolve().parent
TT, DD, V = 16, 2304, 96
SCALE = math.sqrt(DD)  # 48.0, exact


def main():
    rng = np.random.default_rng(0x5CA1E)
    table = rng.standard_normal((V, DD)).astype(np.float32)
    ids = rng.integers(0, V, size=TT, dtype=np.uint32)
    gold = (table[ids] * np.float32(SCALE)).astype(np.float32)

    with open(HERE / "data", "w") as f:
        f.write("// @generated by gen_data.py -- Gemma-2 scaled embedding gather (TABLE[ids]*sqrt(D))\n")
        f.write("#include <stdint.h>\n")
        f.write(f"#define VERIFY_COUNT {TT * DD}\n")
        f.write(f"static const uint32_t TT = {TT};\nstatic const uint32_t DD = {DD};\n")
        G.emit_f32(f, "table_raw", table, dims=f"[{V * DD}]", ncol=8)
        G.emit_u32(f, "ids_raw", ids, dims=f"[{TT}]")
        G.emit_f32(f, "out_raw", np.zeros(TT * DD, np.float32), dims=f"[{TT * DD}]", ncol=8)
        G.emit_f32(f, "gold_raw", gold, dims=f"[{TT * DD}]", ncol=8)
        G.emit_f32(f, "tls_guard", np.zeros(1024, np.float32), dims="[1024]", ncol=8)
    print(f"wrote embed_scale data TT={TT} DD={DD} V={V}")


if __name__ == "__main__":
    main()
