// Auto-composed by radiance_muon._bundle_kernel from CompGen's
// bundle/generated_kernels/* + payload.mlir + execution_plan.yaml +
// golden_inputs.pt + golden_outputs.pt.
//
// Per-region compute callbacks come from the
// radiance_muon_elementwise provider verbatim. The pack contributes
// data baking, dispatch sequencing, and verification.
#include <mu_intrinsics.h>
#include <mu_schedule.h>
#include <stdint.h>

#define N 4

// ========== region add_0 (op=aten_add) ==========
// Auto-generated by RadianceMuonElementwiseProvider.
// region_id = add_0
// op_family = add
// arity     = binary
// N         = 4
//
// Compute-only emit. The pack's composer wraps this with includes,
// data arrays, intermediate buffers, dispatch sequencing in
// execution_order, and a final on-GPU bit-compare against the model's
// expected output.
//
// Stride loop ``i = tid; i += nthreads`` is **load-bearing**: a
// scalar single-thread emit (or even ``tid == 0`` gate) blows up
// Muon's ipdom (immediate post-dominator) stack at N ≥ ~32 when
// combined with the verify kernel's per-element check. Striding
// across lanes keeps each lane's iteration count and divergence
// shallow enough to fit. relu's branch-free ``__builtin_fmaxf``
// keeps the per-element op divergence-free.

struct compgen_region_add_0_args {
  __global float* A;
  __global float* B;
  __global float* C;
};

static inline void compgen_region_add_0_compute(
    void* arg, uint32_t tid, uint32_t nthreads, uint32_t /*blk*/) {
  auto* a = reinterpret_cast<compgen_region_add_0_args*>(arg);
  for (uint32_t i = tid; i < 4; i += nthreads) {
    a->C[i] = a->A[i] + a->B[i];
  }
}

// ========== region relu_relu (op=aten_relu_default) ==========
// Auto-generated by RadianceMuonElementwiseProvider.
// region_id = relu_relu
// op_family = relu
// arity     = unary
// N         = 4
//
// Compute-only emit. The pack's composer wraps this with includes,
// data arrays, intermediate buffers, dispatch sequencing in
// execution_order, and a final on-GPU bit-compare against the model's
// expected output.
//
// Stride loop ``i = tid; i += nthreads`` is **load-bearing**: a
// scalar single-thread emit (or even ``tid == 0`` gate) blows up
// Muon's ipdom (immediate post-dominator) stack at N ≥ ~32 when
// combined with the verify kernel's per-element check. Striding
// across lanes keeps each lane's iteration count and divergence
// shallow enough to fit. relu's branch-free ``__builtin_fmaxf``
// keeps the per-element op divergence-free.

struct compgen_region_relu_relu_args {
  __global float* A;
  __global float* C;
};

static inline void compgen_region_relu_relu_compute(
    void* arg, uint32_t tid, uint32_t nthreads, uint32_t /*blk*/) {
  auto* a = reinterpret_cast<compgen_region_relu_relu_args*>(arg);
  for (uint32_t i = tid; i < 4; i += nthreads) {
    a->C[i] = __builtin_fmaxf(a->A[i], 0.0f);
  }
}

struct compgen_pack_add_0_args {
  __global float* A;
  __global float* B;
  __global float* C;
};

static void compgen_pack_add_0_callback(
    void* arg, uint32_t tid, uint32_t nthreads, uint32_t blk) {
  auto* a = reinterpret_cast<compgen_pack_add_0_args*>(arg);
  compgen_region_add_0_args inner = { a->A, a->B, a->C };
  compgen_region_add_0_compute(&inner, tid, nthreads, blk);
}

struct compgen_pack_relu_relu_args {
  __global float* A;
  __global float* C;
};

static void compgen_pack_relu_relu_callback(
    void* arg, uint32_t tid, uint32_t nthreads, uint32_t blk) {
  auto* a = reinterpret_cast<compgen_pack_relu_relu_args*>(arg);
  compgen_region_relu_relu_args inner = { a->A, a->C };
  compgen_region_relu_relu_compute(&inner, tid, nthreads, blk);
}

__global float A_data_0[4] = { 0x1.495cc80000000p+0f, 0x1.bd0c200000000p-3f, 0x1.0114940000000p-1f, 0x1.2cab900000000p-3f };
__global float A_data_1[4] = { -0x1.9efb5e0000000p-1f, 0x1.c7213c0000000p+0f, -0x1.d47d0a0000000p-6f, 0x1.032a200000000p-3f };
__global float T_add_0[4] = { 0.0f, 0.0f, 0.0f, 0.0f };
__global float compgen_host_out_buf[N] = { -0x1.dbf59cp+126f, -0x1.dbf59cp+126f, -0x1.dbf59cp+126f, -0x1.dbf59cp+126f };

int main() {
  {
    compgen_pack_add_0_args a = { A_data_0, A_data_1, T_add_0 };
    mu_schedule(compgen_pack_add_0_callback, &a, 1);
  }
  {
    compgen_pack_relu_relu_args a = { T_add_0, compgen_host_out_buf };
    mu_schedule(compgen_pack_relu_relu_callback, &a, 1);
  }
  return 0;
}
