// Auto-composed by radiance_muon._bundle_kernel from CompGen's
// bundle/generated_kernels/* + payload.mlir + execution_plan.yaml +
// golden_inputs.pt + golden_outputs.pt.
//
// Per-region compute callbacks come from the
// radiance_muon_elementwise provider verbatim. The pack contributes
// data baking, dispatch sequencing, and verification.
#include <mu_intrinsics.h>
#include <mu_schedule.h>
#include <stdint.h>

#define N 4

// ========== region elementwise_0 (op=aten_sub) ==========
// Auto-generated by RadianceMuonElementwiseProvider.
// region_id = elementwise_0
// op_family = sub
// arity     = binary
// N         = 4
//
// Compute-only emit. The pack's composer wraps this with includes,
// data arrays, intermediate buffers, dispatch sequencing in
// execution_order, and a final on-GPU bit-compare against the model's
// expected output.
//
// Stride loop ``i = tid; i += nthreads`` is **load-bearing**: a
// scalar single-thread emit (or even ``tid == 0`` gate) blows up
// Muon's ipdom (immediate post-dominator) stack at N ≥ ~32 when
// combined with the verify kernel's per-element check. Striding
// across lanes keeps each lane's iteration count and divergence
// shallow enough to fit. relu's branch-free ``__builtin_fmaxf``
// keeps the per-element op divergence-free.

struct compgen_region_elementwise_0_args {
  __global float* A;
  __global float* B;
  __global float* C;
};

static inline void compgen_region_elementwise_0_compute(
    void* arg, uint32_t tid, uint32_t nthreads, uint32_t /*blk*/) {
  auto* a = reinterpret_cast<compgen_region_elementwise_0_args*>(arg);
  for (uint32_t i = tid; i < 4; i += nthreads) {
    a->C[i] = a->A[i] - a->B[i];
  }
}

struct compgen_pack_elementwise_0_args {
  __global float* A;
  __global float* B;
  __global float* C;
};

static void compgen_pack_elementwise_0_callback(
    void* arg, uint32_t tid, uint32_t nthreads, uint32_t blk) {
  auto* a = reinterpret_cast<compgen_pack_elementwise_0_args*>(arg);
  compgen_region_elementwise_0_args inner = { a->A, a->B, a->C };
  compgen_region_elementwise_0_compute(&inner, tid, nthreads, blk);
}

struct compgen_pack_verify_args {
  __global float* C;
  __global float* EXP;
  __global volatile uint32_t* mismatch;
};

static void compgen_pack_verify_kernel(
    void* arg, uint32_t tid, uint32_t /*nthreads*/, uint32_t /*blk*/) {
  auto* a = reinterpret_cast<compgen_pack_verify_args*>(arg);
  if (tid != 0) return;
  // Accumulate any-mismatch via XOR-OR rather than per-iteration
  // ``if`` checks — at moderate N (≥32) the per-iteration branch
  // form pushes onto Muon's ipdom (immediate post-dominator) stack
  // without timely pops and the sim asserts ``ipdom stack is full``.
  // Branch-free accumulation keeps the loop body straight-line.
  uint32_t mismatch_bits = 0u;
  for (uint32_t i = 0; i < 4; ++i) {
    uint32_t got = __builtin_bit_cast(uint32_t, a->C[i]);
    uint32_t exp = __builtin_bit_cast(uint32_t, a->EXP[i]);
    mismatch_bits |= (got ^ exp);
  }
  if (mismatch_bits != 0u) {
    *a->mismatch = 0xDEADBEEFu;
    for (;;) { /* never go idle — sim cycle-budget will fire */ }
  }
}

__global float A_data_0[4] = { 0x1.a573ec0000000p+0f, -0x1.7f438a0000000p-3f, 0x1.39ac4c0000000p-2f, -0x1.87f5920000000p+0f };
__global float A_data_1[4] = { 0x1.88f7860000000p-1f, -0x1.3f5f0e0000000p-4f, 0x1.a47aee0000000p-1f, 0x1.435bd20000000p-1f };
__global float T_elementwise_0[4] = { 0.0f, 0.0f, 0.0f, 0.0f };
__global float EXP_data[N] = { 0x1.c1f0520000000p-1f, -0x1.bf28060000000p-4f, -0x1.07a4c80000000p-1f, -0x1.14d1be0000000p+1f };
__global volatile uint32_t mismatch_flag = 0u;

int main() {
  {
    compgen_pack_elementwise_0_args a = { A_data_0, A_data_1, T_elementwise_0 };
    mu_schedule(compgen_pack_elementwise_0_callback, &a, 1);
  }
  {
    compgen_pack_verify_args a = { T_elementwise_0, EXP_data, &mismatch_flag };
    mu_schedule(compgen_pack_verify_kernel, &a, 1);
  }
  return 0;
}
