#!/usr/bin/env python3
"""Generate `data` for SigLIP patch/conv embedding.

The SmolVLA vision tower (SmolVLM2-500M SigLIP) turns an image into patch tokens
with a Conv2d(3 -> 768, kernel=16, stride=16) + bias, then adds a learned
position_embedding. Confirmed from the real weight manifest:
  vision_model.embeddings.patch_embedding.weight [768, 3, 16, 16] + .bias [768]
  vision_model.embeddings.position_embedding.weight [1024, 768]
and the captured graph (aten.convolution + add of the position table).

Because stride == kernel (16), the patches are NON-OVERLAPPING, so the conv is
exactly a patchify (im2col) + GEMM + bias:

  patch p at grid (gy,gx), K = 3*16*16 = 768 :
    col[p, (c,ky,kx)] = image[c, gy*16+ky, gx*16+kx]
    out[p, oc] = sum_K col[p,K] * W[oc, (c,ky,kx)] + bias[oc] + pos_embed[p, oc]

The GEMM itself is already covered; the NEW piece is the patchify addressing
(conv-as-GEMM) + the per-channel bias + the position-embedding add. Dims here:
image 3x64x64 -> 4x4 = 16 patches, K = 768 (the real 16x16x3 patch), OC = 64
(a representative tile of the real 768 embedding channels). All fp32.

Golden = numpy fp32 with identical arithmetic (a strided im2col + matmul).
Emit helpers come from the shared golden module (lib/golden).
"""
import pathlib
import sys

import numpy as np

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parents[2] / "lib" / "golden"))
import golden as G

HERE = pathlib.Path(__file__).resolve().parent

C = 3              # image channels
PATCH = 16         # conv kernel == stride (non-overlapping)
IMG = 64           # image H = W (representative crop; real is 512)
GRID = IMG // PATCH          # 4  -> GRID*GRID = 16 patches
NP = GRID * GRID             # 16 patch tokens
K = C * PATCH * PATCH        # 768  (the real per-patch flattened dim)
OC = 64            # output-channel tile (of the real 768 embed dim)


def main():
    rng = np.random.default_rng(0x9A7C)
    image = (rng.standard_normal((C, IMG, IMG))).astype(np.float32)          # [3,64,64]
    W = (0.05 * rng.standard_normal((OC, C, PATCH, PATCH))).astype(np.float32)  # [OC,3,16,16]
    bias = (0.1 * rng.standard_normal(OC)).astype(np.float32)
    pos = (0.1 * rng.standard_normal((NP, OC))).astype(np.float32)            # position embed tile

    # numpy golden: strided im2col then matmul
    col = np.zeros((NP, K), dtype=np.float32)
    for gy in range(GRID):
        for gx in range(GRID):
            p = gy * GRID + gx
            patch = image[:, gy * PATCH:(gy + 1) * PATCH, gx * PATCH:(gx + 1) * PATCH]  # [3,16,16]
            col[p] = patch.reshape(-1)                       # (c,ky,kx) row-major == W flatten
    Wf = W.reshape(OC, K)
    out = (col @ Wf.T + bias[None, :] + pos).astype(np.float32)   # [NP, OC]

    with open(HERE / "data", "w") as f:
        f.write("// @generated by gen_data.py -- SigLIP patch/conv embedding (patchify+GEMM+bias+pos)\n")
        f.write("#include <stdint.h>\n")
        f.write(f"#define PE_C {C}\n#define PE_PATCH {PATCH}\n#define PE_IMG {IMG}\n")
        f.write(f"#define PE_GRID {GRID}\n#define PE_NP {NP}\n#define PE_K {K}\n#define PE_OC {OC}\n")
        f.write(f"#define VERIFY_COUNT {NP * OC}\n")
        G.emit_f32(f, "image_raw", image, dims="[PE_C * PE_IMG * PE_IMG]", ncol=8)
        G.emit_f32(f, "weight_raw", W, dims="[PE_OC * PE_K]", ncol=8)          # W[oc,(c,ky,kx)] flattened
        G.emit_f32(f, "bias_raw", bias, dims="[PE_OC]", ncol=8)
        G.emit_f32(f, "pos_raw", pos, dims="[PE_NP * PE_OC]", ncol=8)
        G.emit_f32(f, "out_raw", np.zeros(NP * OC, dtype=np.float32), dims="[PE_NP * PE_OC]", ncol=8)
        G.emit_f32(f, "gold_raw", out, dims="[PE_NP * PE_OC]", ncol=8)
    print(f"wrote data patches={NP} K={K} OC={OC} img={C}x{IMG}x{IMG}")


if __name__ == "__main__":
    main()
