#!/usr/bin/env python3
"""Generate `data` for the fused QKV(MX fp4 K=2048) + RoPE(SIMT) kernel, head_dim=64.

  out[M,N] (bf16) = RoPE( bf16( X[M,K] @ W[K,N] ) )

The MX-Gemmini fp4 matmul leaves C(bf16) in SMEM; a 4-warp SIMT RoPE epilogue reads C
from SMEM and writes rotated bf16 to GMEM. Golden = RoPE(mx_matmul(X@W)), bit-exact
(bf16 truncation + float32 RoPE math match the kernel; RoPE has no division).

All primitives, the MX matmul, and emit come from the shared golden module (lib/golden).
"""
import pathlib
import sys

import numpy as np

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parents[2] / "lib" / "golden"))
import golden as G

HERE = pathlib.Path(__file__).resolve().parent
M, N, K = 64, 64, 2048          # head_dim=64, model dim K=2048
HALF = N // 2
THETA = 10000.0


def main():
    GK, GN = K // G.GROUP, N // G.GROUP
    rng = np.random.default_rng(0xC0FFEE)

    A_nib = G.rand_fp4(rng, M * K).reshape(M, K)
    B_nib = G.rand_fp4(rng, K * N).reshape(K, N)
    A_hw = G.pack_axis0(A_nib)   # [M/2][K]
    B_in = G.pack_axis1(B_nib)   # [K][N/2]
    SA = rng.integers(0x7B, 0x83, size=(GK, M), dtype=np.uint8)
    SB = rng.integers(0x7B, 0x83, size=(GK, N), dtype=np.uint8)

    C_bf16 = G.mx_matmul(A_hw, B_in, SA, SB, M, N, K, "fp4", tmpdir=str(HERE / "_gen"))

    cos_h, sin_h, cos_full, sin_full = G.rope_caches(M, N, THETA)
    o = G.rope_apply(G.bf16_to_f32(C_bf16), cos_h, sin_h)
    gold = np.empty((M, N), dtype=np.uint16)
    gold[:, :HALF] = G.f_to_bf16(o[:, :HALF])
    gold[:, HALF:] = G.f_to_bf16(o[:, HALF:])
    cos_bits = cos_full.view(np.uint32).reshape(M, N)
    sin_bits = sin_full.view(np.uint32).reshape(M, N)

    with open(HERE / "data", "w") as f:
        f.write("// @generated by gen_data.py -- fused QKV(MX fp4 K=2048) + RoPE(SIMT), head_dim=64\n")
        f.write("#include <stdint.h>\n")
        f.write(f"#define MATMUL_M {M}\n#define MATMUL_N {N}\n#define MATMUL_K {K}\n")
        f.write(f"#define MATMUL_GK {GK}\n#define MATMUL_GN {GN}\n")
        f.write(f"#define VERIFY_COUNT {M * N}\n")
        G.emit(f, "uint8_t", "A_in_hw", "[MATMUL_M / 2][MATMUL_K]", A_hw)
        G.emit(f, "uint8_t", "B_in", "[MATMUL_K][MATMUL_N / 2]", B_in)
        G.emit(f, "uint8_t", "A_scales_row", "[MATMUL_GK][MATMUL_M]", SA)
        G.emit(f, "uint8_t", "B_scales_col", "[MATMUL_GK][MATMUL_N]", SB)
        G.emit(f, "uint32_t", "cos_bits", "[MATMUL_M][MATMUL_N]", cos_bits)
        G.emit(f, "uint32_t", "sin_bits", "[MATMUL_M][MATMUL_N]", sin_bits)
        f.write("__global uint16_t C_raw[MATMUL_M * MATMUL_N] = {0};\n")
        G.emit(f, "uint16_t", "gold_raw", "[MATMUL_M * MATMUL_N]", gold)
        f.write("static const uint8_t *A_in = &A_in_hw[0][0];\n")
        f.write("static const float* cos_raw = (const float*)&cos_bits[0][0];\n")
        f.write("static const float* sin_raw = (const float*)&sin_bits[0][0];\n")
        f.write("__global float tls_guard[1024] = {0};\n")
    print(f"wrote data  M={M} N={N} K={K} GK={GK} GN={GN} HALF={HALF}")


if __name__ == "__main__":
    main()
