// Auto-composed by radiance_muon._bundle_kernel from CompGen's
// bundle/generated_kernels/* + payload.mlir + execution_plan.yaml +
// golden_inputs.pt + golden_outputs.pt.
//
// Per-region compute callbacks come from the
// radiance_muon_elementwise provider verbatim. The pack contributes
// data baking, dispatch sequencing, and verification.
#include <mu_intrinsics.h>
#include <mu_schedule.h>
#include <stdint.h>

#define N 1

// ========== region sum_sum_1 (op=aten_sum_dim_IntList) ==========
// Auto-generated by RadianceMuonReductionProvider.
// region_id  = sum_sum_1
// op_family  = sum_dim_IntList
// arity      = unary
// N          = 1
// input_n    = 8
//
// Compute-only emit. The pack composer wraps with main + data + dispatch.
// A: rank-N input flattened to 8 elements.
// C: scalar output (1 element).

struct compgen_region_sum_sum_1_args {
  __global float* A;   // input, flat length 8
  __global float* C;   // scalar output (length 1)
};

static inline void compgen_region_sum_sum_1_compute(
    void* arg, uint32_t tid, uint32_t /*nthreads*/, uint32_t /*blk*/) {
  if (tid != 0) return;
  auto* a = reinterpret_cast<compgen_region_sum_sum_1_args*>(arg);
  float acc = 0.0f;
  for (uint32_t i = 0; i < 8; ++i) {
    acc += a->A[i];
  }
  a->C[0] = acc;
}

struct compgen_pack_sum_sum_1_args {
  __global float* A;
  __global float* C;
};

static void compgen_pack_sum_sum_1_callback(
    void* arg, uint32_t tid, uint32_t nthreads, uint32_t blk) {
  auto* a = reinterpret_cast<compgen_pack_sum_sum_1_args*>(arg);
  compgen_region_sum_sum_1_args inner = { a->A, a->C };
  compgen_region_sum_sum_1_compute(&inner, tid, nthreads, blk);
}

struct compgen_pack_verify_args {
  __global float* C;
  __global float* EXP;
  __global volatile uint32_t* mismatch;
};

static void compgen_pack_verify_kernel(
    void* arg, uint32_t tid, uint32_t /*nthreads*/, uint32_t /*blk*/) {
  auto* a = reinterpret_cast<compgen_pack_verify_args*>(arg);
  if (tid != 0) return;
  // Accumulate any-mismatch via XOR-OR rather than per-iteration
  // ``if`` checks — at moderate N (≥32) the per-iteration branch
  // form pushes onto Muon's ipdom (immediate post-dominator) stack
  // without timely pops and the sim asserts ``ipdom stack is full``.
  // Branch-free accumulation keeps the loop body straight-line.
  uint32_t mismatch_bits = 0u;
  for (uint32_t i = 0; i < 1; ++i) {
    uint32_t got = __builtin_bit_cast(uint32_t, a->C[i]);
    uint32_t exp = __builtin_bit_cast(uint32_t, a->EXP[i]);
    mismatch_bits |= (got ^ exp);
  }
  if (mismatch_bits != 0u) {
    *a->mismatch = 0xDEADBEEFu;
    for (;;) { /* never go idle — sim cycle-budget will fire */ }
  }
}

__global float A_data_0[8] = { 0x1.00a8380000000p+0f, 0x1.d348560000000p+0f, 0x1.aab58c0000000p-3f, 0x1.2559de0000000p+0f, -0x1.45255e0000000p+1f, 0x1.790d220000000p-3f, 0x1.ea94720000000p-2f, -0x1.0e690e0000000p+0f };
__global float T_sum_sum_1[1] = { 0.0f };
__global float EXP_data[N] = { 0x1.3fb4160000000p+0f };
__global volatile uint32_t mismatch_flag = 0u;

int main() {
  {
    compgen_pack_sum_sum_1_args a = { A_data_0, T_sum_sum_1 };
    mu_schedule(compgen_pack_sum_sum_1_callback, &a, 1);
  }
  {
    compgen_pack_verify_args a = { T_sum_sum_1, EXP_data, &mismatch_flag };
    mu_schedule(compgen_pack_verify_kernel, &a, 1);
  }
  return 0;
}
