PROJECT = tuning_writeback_wb_capacity

VX_SRCS = kernel.cpp
BINFILES := args.bin

VORTEX_KN_PATH ?= $(realpath ../../../../lib)
GEMMINI_SW_PATH ?= $(realpath ../../../../lib/gemmini)

include ../../../common.mk
