// Auto-composed by radiance_muon._bundle_kernel from CompGen's
// bundle/generated_kernels/* + payload.mlir + execution_plan.yaml +
// golden_inputs.pt + golden_outputs.pt.
//
// Per-region compute callbacks come from the
// radiance_muon_elementwise provider verbatim. The pack contributes
// data baking, dispatch sequencing, and verification.
#include <mu_intrinsics.h>
#include <mu_schedule.h>
#include <stdint.h>

#define N 64

// ========== region add_0 (op=aten_add) ==========
// Auto-generated by RadianceMuonHandwrittenVecAddProvider.
// region_id  = add_0
// op_family  = add
// arity      = binary
// N          = 64
//
// Compute body lifted verbatim from
//   /scratch2/agustin/radiance-kernels/kernels/vecadd/kernel.cpp
// (only the ``vecadd`` callback — own main, ``VecAddArgs`` struct,
// and ``#include "data"`` are stripped because our composer wraps
// with its standard main + golden-baked input arrays). The stride
// loop ``i = tid; i < n; i += nthreads`` preserves the original's
// multi-warp parallelism so this exercises real SIMT hardware
// rather than the auto-generated scalar fallback.

struct compgen_region_add_0_args {
  __global float* A;
  __global float* B;
  __global float* C;
};

static inline void compgen_region_add_0_compute(
    void* arg,
    uint32_t tid_in_threadblock,
    uint32_t threads_per_threadblock,
    uint32_t /*threadblock_id*/) {
  auto* a = reinterpret_cast<compgen_region_add_0_args*>(arg);
  for (uint32_t i = tid_in_threadblock; i < 64; i += threads_per_threadblock) {
    a->C[i] = a->A[i] + a->B[i];
  }
}

struct compgen_pack_add_0_args {
  __global float* A;
  __global float* B;
  __global float* C;
};

static void compgen_pack_add_0_callback(
    void* arg, uint32_t tid, uint32_t nthreads, uint32_t blk) {
  auto* a = reinterpret_cast<compgen_pack_add_0_args*>(arg);
  compgen_region_add_0_args inner = { a->A, a->B, a->C };
  compgen_region_add_0_compute(&inner, tid, nthreads, blk);
}

struct compgen_pack_verify_args {
  __global float* C;
  __global float* EXP;
  __global volatile uint32_t* mismatch;
};

static void compgen_pack_verify_kernel(
    void* arg, uint32_t tid, uint32_t /*nthreads*/, uint32_t /*blk*/) {
  auto* a = reinterpret_cast<compgen_pack_verify_args*>(arg);
  if (tid != 0) return;
  // Accumulate any-mismatch via XOR-OR rather than per-iteration
  // ``if`` checks — at moderate N (≥32) the per-iteration branch
  // form pushes onto Muon's ipdom (immediate post-dominator) stack
  // without timely pops and the sim asserts ``ipdom stack is full``.
  // Branch-free accumulation keeps the loop body straight-line.
  uint32_t mismatch_bits = 0u;
  for (uint32_t i = 0; i < 64; ++i) {
    uint32_t got = __builtin_bit_cast(uint32_t, a->C[i]);
    uint32_t exp = __builtin_bit_cast(uint32_t, a->EXP[i]);
    mismatch_bits |= (got ^ exp);
  }
  if (mismatch_bits != 0u) {
    *a->mismatch = 0xDEADBEEFu;
    for (;;) { /* never go idle — sim cycle-budget will fire */ }
  }
}

__global float A_data_0[64] = { 0x1.11562c0000000p-2f, -0x1.737c160000000p-1f, 0x1.988b7c0000000p-1f, 0x1.5462080000000p-2f, -0x1.b5087c0000000p-2f, 0x1.0e90360000000p+0f, 0x1.1304720000000p+0f, -0x1.a6d75a0000000p-2f, -0x1.2265180000000p-1f, 0x1.e353aa0000000p-2f, 0x1.2e080a0000000p+0f, -0x1.b9ee3c0000000p-1f, -0x1.10d1620000000p-2f, -0x1.9ade280000000p-2f, -0x1.06e38e0000000p+0f, 0x1.41a56a0000000p+0f, 0x1.020b5e0000000p+0f, 0x1.d221520000000p+0f, 0x1.2840420000000p+0f, -0x1.d3af4e0000000p-1f, -0x1.d3ff3a0000000p+1f, -0x1.2d2d560000000p+1f, 0x1.6bcac80000000p-3f, -0x1.be17300000000p-2f, -0x1.a120360000000p+0f, -0x1.aa4b4e0000000p-2f, -0x1.fb4ede0000000p-5f, -0x1.2f70bc0000000p+0f, -0x1.2719e00000000p-1f, 0x1.6acf1c0000000p-1f, -0x1.3230740000000p+1f, -0x1.8266680000000p-4f, 0x1.f6a5160000000p-5f, -0x1.be43080000000p+0f, -0x1.39c9240000000p+1f, -0x1.1b499e0000000p-1f, 0x1.8a40e60000000p-3f, 0x1.5a55880000000p-1f, -0x1.0e6d440000000p-1f, 0x1.17c7320000000p-1f, 0x1.2bc5900000000p+0f, -0x1.6329b60000000p-1f, 0x1.ee16920000000p-1f, -0x1.d30f1e0000000p+0f, 0x1.8871a60000000p-3f, -0x1.861ca60000000p-3f, -0x1.d99c8c0000000p-2f, 0x1.f1429e0000000p-1f, -0x1.8def940000000p+0f, -0x1.d1d8400000000p-2f, -0x1.721dee0000000p-1f, 0x1.ee54940000000p-1f, 0x1.b500a00000000p-3f, 0x1.0936140000000p+1f, -0x1.208c980000000p-5f, 0x1.aa6f500000000p-3f, 0x1.2812ee0000000p-1f, -0x1.12bb0e0000000p-1f, -0x1.390f900000000p-1f, 0x1.75c5740000000p-3f, 0x1.d63b7c0000000p-5f, -0x1.62eec80000000p+0f, -0x1.3bc6d00000000p+0f, -0x1.a70c140000000p-1f };
__global float A_data_1[64] = { 0x1.cd539a0000000p-4f, -0x1.ee2f980000000p-2f, 0x1.b92b080000000p-1f, -0x1.31c2960000000p+0f, -0x1.9b5da40000000p-1f, -0x1.b412140000000p+0f, 0x1.e3387e0000000p+1f, -0x1.a02e1a0000000p-1f, 0x1.92beb40000000p-2f, 0x1.2030200000000p-4f, 0x1.54b0ac0000000p+0f, -0x1.1adf120000000p+1f, -0x1.5066e80000000p+0f, -0x1.2dd3b80000000p-4f, 0x1.a70a1a0000000p-1f, -0x1.d5c2980000000p-3f, 0x1.bd2bee0000000p-2f, 0x1.a0f49c0000000p+0f, -0x1.1940900000000p-1f, -0x1.f8cbf60000000p-3f, 0x1.0a40180000000p+1f, -0x1.56fc5a0000000p+0f, 0x1.3cf6060000000p+0f, 0x1.5aa6200000000p-1f, 0x1.a8dad80000000p-1f, 0x1.c0d7800000000p-1f, -0x1.a0d3b00000000p-5f, 0x1.fd9c4c0000000p+0f, 0x1.82d0f00000000p-1f, 0x1.7e7a940000000p+0f, 0x1.4fb8580000000p-1f, -0x1.e7d5fa0000000p+0f, -0x1.31bae80000000p+0f, 0x1.77848e0000000p-1f, 0x1.2434a60000000p+0f, 0x1.010ffa0000000p-1f, -0x1.010e060000000p-1f, 0x1.4919160000000p-1f, 0x1.9400180000000p+1f, -0x1.5643a60000000p-1f, 0x1.a6d4300000000p-1f, 0x1.7572e60000000p-4f, 0x1.286d460000000p-8f, 0x1.f831f40000000p-1f, -0x1.95da8a0000000p+0f, 0x1.0da8100000000p-4f, 0x1.f271a40000000p-1f, 0x1.4115000000000p-4f, 0x1.4ffc340000000p-2f, -0x1.9237f00000000p+1f, 0x1.11dc640000000p-1f, -0x1.611d060000000p-2f, 0x1.4203100000000p-3f, -0x1.e6baa00000000p-3f, -0x1.5906fc0000000p+0f, 0x1.26f79c0000000p+0f, 0x1.8c5f140000000p-1f, 0x1.9678320000000p-2f, 0x1.d2d5bc0000000p+0f, 0x1.b57b060000000p+0f, -0x1.c4efca0000000p+0f, -0x1.4eebe20000000p-1f, 0x1.9bd0dc0000000p-2f, -0x1.0dead60000000p+0f };
__global float T_add_0[64] = { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f };
__global float EXP_data[N] = { 0x1.84ab120000000p-2f, -0x1.3549f00000000p+0f, 0x1.a8db420000000p+0f, -0x1.b954280000000p-1f, -0x1.3af0f00000000p+0f, -0x1.4b03bc0000000p-1f, 0x1.365d5c0000000p+2f, -0x1.39cce40000000p+0f, -0x1.6416f80000000p-3f, 0x1.15afd80000000p-1f, 0x1.415c5c0000000p+1f, -0x1.895aa00000000p+1f, -0x1.949b400000000p+0f, -0x1.e653160000000p-2f, -0x1.9af4080000000p-3f, 0x1.06ed180000000p+0f, 0x1.71565a0000000p+0f, 0x1.b98af80000000p+1f, 0x1.373ff40000000p-1f, -0x1.28f1260000000p+0f, -0x1.937e440000000p+0f, -0x1.d8ab840000000p+1f, 0x1.6a6f600000000p+0f, 0x1.ee6a200000000p-3f, -0x1.9965940000000p-1f, 0x1.d763b20000000p-2f, -0x1.ce11480000000p-4f, 0x1.9c57200000000p-1f, 0x1.6edc400000000p-3f, 0x1.19f1100000000p+1f, -0x1.bc84bc0000000p+0f, -0x1.fffc600000000p+0f, -0x1.2205c00000000p+0f, -0x1.0280c00000000p+0f, -0x1.4f5da20000000p+0f, -0x1.a39a400000000p-5f, -0x1.3cfb980000000p-2f, 0x1.51b7500000000p+0f, 0x1.5064c80000000p+1f, -0x1.f3e3a00000000p-4f, 0x1.ff2fa80000000p+0f, -0x1.347b5a0000000p-1f, 0x1.f0676c0000000p-1f, -0x1.adec480000000p-1f, -0x1.64cc560000000p+0f, -0x1.fe913c0000000p-4f, 0x1.05a35e0000000p-1f, 0x1.0cb2a00000000p+0f, -0x1.39f0880000000p+0f, -0x1.cc72f80000000p+1f, -0x1.8106280000000p-3f, 0x1.3dc6100000000p-1f, 0x1.7b81d80000000p-2f, 0x1.d594d40000000p+0f, -0x1.620b600000000p+0f, 0x1.5c45860000000p+0f, 0x1.5a39000000000p+0f, -0x1.1dfbd40000000p-3f, 0x1.364df40000000p+0f, 0x1.e433b40000000p+0f, -0x1.b63dee0000000p+0f, -0x1.05325c0000000p+1f, -0x1.a9a5320000000p-1f, -0x1.e170e00000000p+0f };
__global volatile uint32_t mismatch_flag = 0u;

int main() {
  {
    compgen_pack_add_0_args a = { A_data_0, A_data_1, T_add_0 };
    mu_schedule(compgen_pack_add_0_callback, &a, 4);
  }
  {
    compgen_pack_verify_args a = { T_add_0, EXP_data, &mismatch_flag };
    mu_schedule(compgen_pack_verify_kernel, &a, 1);
  }
  return 0;
}
