#!/usr/bin/env python3
"""Generate `data` for RMSNorm fused into the matmul PROLOGUE.

A SIMT prologue reads X[M][K] (bf16), computes RMSNorm per row, quantizes to fp8 e4m3
into the exact GMEM buffer mxgemm reads its A operand from, then the fp8 mxgemm runs.
Golden = mx_matmul( fp8(RMSNorm(X)), W ), using the same fp8 encoder the kernel uses.

All primitives, the MX matmul, and emit come from the shared golden module (lib/golden).
"""
import pathlib
import sys

import numpy as np

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parents[2] / "lib" / "golden"))
import golden as G

HERE = pathlib.Path(__file__).resolve().parent
M, N, K = 64, 64, 256
EPS = 1e-5


def main():
    GK, GN = K // G.GROUP, N // G.GROUP
    rng = np.random.default_rng(0x5A17)

    X = G.bf16_trunc(rng.standard_normal((M, K)).astype(np.float32))
    gamma = G.bf16_trunc((0.75 + 0.5 * rng.random(K)).astype(np.float32))

    # RMSNorm + fp8 quant, matching the kernel's float32 path exactly.
    xn = G.rmsnorm(X, gamma, EPS)
    A_codes = np.zeros((M, K), dtype=np.uint8)
    for m in range(M):
        for k in range(K):
            A_codes[m, k] = G.fp8_code(xn[m, k])

    B_in = G.rand_fp8(rng, K * N).reshape(K, N)
    SA = np.full((GK, M), 0x7F, dtype=np.uint8)   # prologue owns the row scaling
    SB = rng.integers(0x7B, 0x83, size=(GK, N), dtype=np.uint8)

    gold = G.mx_matmul(A_codes, B_in, SA, SB, M, N, K, "fp8", tmpdir=str(HERE / "_gen")).astype(np.uint16)

    X_bits = G.f_to_bf16(X)
    g_bits = G.f_to_bf16(gamma)

    with open(HERE / "data", "w") as f:
        f.write("// @generated by gen_data.py -- RMSNorm(SIMT prologue) fused into fp8 mxgemm\n")
        f.write("#include <stdint.h>\n")
        f.write(f"#define MATMUL_M {M}\n#define MATMUL_N {N}\n#define MATMUL_K {K}\n")
        f.write(f"#define MATMUL_GK {GK}\n#define MATMUL_GN {GN}\n")
        f.write(f"#define VERIFY_COUNT {M * N}\n")
        f.write(f"#define RMS_EPS {EPS:.8e}f\n")
        G.emit(f, "uint16_t", "X_bf16", "[MATMUL_M][MATMUL_K]", X_bits)
        G.emit(f, "uint16_t", "gamma_bf16", "[MATMUL_K]", g_bits.reshape(1, K))
        G.emit(f, "uint8_t", "B_in", "[MATMUL_K][MATMUL_N]", B_in)
        G.emit(f, "uint8_t", "A_scales_row", "[MATMUL_GK][MATMUL_M]", SA)
        G.emit(f, "uint8_t", "B_scales_col", "[MATMUL_GK][MATMUL_N]", SB)
        f.write("__global uint8_t A_store[MATMUL_M * MATMUL_K] = {0};  // fp8 A written by prologue\n")
        f.write("__global uint16_t C_raw[MATMUL_M * MATMUL_N] = {0};\n")
        G.emit(f, "uint16_t", "gold_raw", "[MATMUL_M * MATMUL_N]", gold)
        f.write("static const uint8_t *A_in = "
                "reinterpret_cast<const uint8_t*>(reinterpret_cast<uint32_t>(&A_store[0]));\n")
        f.write("__global float tls_guard[1024] = {0};\n")
    print(f"wrote data  M={M} N={N} K={K} GK={GK} GN={GN}  nonzero A codes={int((A_codes!=0).sum())}/{M*K}")


if __name__ == "__main__":
    main()
