// Auto-composed by radiance_muon._bundle_kernel from CompGen's
// bundle/generated_kernels/* + payload.mlir + execution_plan.yaml +
// golden_inputs.pt + golden_outputs.pt.
//
// Per-region compute callbacks come from the
// radiance_muon_elementwise provider verbatim. The pack contributes
// data baking, dispatch sequencing, and verification.
#include <mu_intrinsics.h>
#include <mu_schedule.h>
#include <stdint.h>

#define N 4

// ========== region matmul_0 (op=linalg.matmul) ==========
// Auto-generated by RadianceMuonMatmulProvider.
// region_id = matmul_0
// op_family = matmul
// M         = 1
// K         = 8
// N         = 4
//
// Compute-only emit. The pack's composer wraps this with includes,
// data arrays (M*K + K*N flat float32 init), an MxN output buffer,
// dispatch sequencing, and verification against the model's golden.

struct compgen_region_matmul_0_args {
  __global float* A;   // M*K row-major
  __global float* B;   // K*N row-major
  __global float* C;   // M*N row-major
};

static inline void compgen_region_matmul_0_compute(
    void* arg, uint32_t tid, uint32_t /*nthreads*/, uint32_t /*blk*/) {
  if (tid != 0) return;
  auto* a = reinterpret_cast<compgen_region_matmul_0_args*>(arg);
  for (uint32_t m = 0; m < 1; ++m) {
    for (uint32_t n = 0; n < 4; ++n) {
      float acc = 0.0f;
      for (uint32_t k = 0; k < 8; ++k) {
        acc += a->A[m * 8 + k] * a->B[k * 4 + n];
      }
      a->C[m * 4 + n] = acc;
    }
  }
}

// ========== region add_0 (op=aten_bias_add) ==========
// Auto-generated by RadianceMuonBiasAddProvider.
// region_id  = add_0
// op_family  = bias_add
// arity      = binary
// N          = 4
// bias_len   = 4
//
// Compute-only emit. The pack composer wraps with main + data + dispatch.
// A: bias vector (length 4)
// B: input matrix (flattened length 4, row-major rows of 4)
// C: output matrix (flattened length 4)
// C[i] = B[i] + A[i % bias_len]

struct compgen_region_add_0_args {
  __global float* A;   // bias, length 4
  __global float* B;   // input matrix, flat length 4
  __global float* C;   // output matrix, flat length 4
};

static inline void compgen_region_add_0_compute(
    void* arg, uint32_t /*tid*/, uint32_t /*nthreads*/, uint32_t /*blk*/) {
  auto* a = reinterpret_cast<compgen_region_add_0_args*>(arg);
  for (uint32_t i = 0; i < 4; ++i) {
    a->C[i] = a->B[i] + a->A[i % 4];
  }
}

struct compgen_pack_matmul_0_args {
  __global float* A;
  __global float* B;
  __global float* C;
};

static void compgen_pack_matmul_0_callback(
    void* arg, uint32_t tid, uint32_t nthreads, uint32_t blk) {
  auto* a = reinterpret_cast<compgen_pack_matmul_0_args*>(arg);
  compgen_region_matmul_0_args inner = { a->A, a->B, a->C };
  compgen_region_matmul_0_compute(&inner, tid, nthreads, blk);
}

struct compgen_pack_add_0_args {
  __global float* A;
  __global float* B;
  __global float* C;
};

static void compgen_pack_add_0_callback(
    void* arg, uint32_t tid, uint32_t nthreads, uint32_t blk) {
  auto* a = reinterpret_cast<compgen_pack_add_0_args*>(arg);
  compgen_region_add_0_args inner = { a->A, a->B, a->C };
  compgen_region_add_0_compute(&inner, tid, nthreads, blk);
}

__global float A_data_0[32] = { 0x1.058aec0000000p-3f, 0x1.f61ba80000000p-3f, 0x1.a22aaa0000000p-6f, -0x1.368e660000000p-3f, -0x1.444c000000000p-2f, -0x1.0f05d80000000p-4f, -0x1.df2ae40000000p-3f, -0x1.513cfc0000000p-2f, -0x1.52d4360000000p-2f, 0x1.6e76700000000p-3f, -0x1.a053fe0000000p-5f, 0x1.298ea20000000p-2f, 0x1.e8869e0000000p-3f, -0x1.2361a40000000p-3f, 0x1.823a080000000p-3f, 0x1.889b720000000p-5f, -0x1.3ae4500000000p-2f, -0x1.6aab840000000p-3f, -0x1.423f4c0000000p-3f, -0x1.4f712a0000000p-3f, -0x1.4130ce0000000p-2f, -0x1.b2f34e0000000p-5f, 0x1.7fcffa0000000p-3f, -0x1.6400c20000000p-2f, 0x1.ad90a00000000p-5f, 0x1.4b314e0000000p-2f, 0x1.e60fd00000000p-3f, -0x1.84ca940000000p-3f, 0x1.9419fc0000000p-4f, -0x1.7898000000000p-3f, -0x1.55f5f00000000p-6f, -0x1.a272640000000p-3f };
__global float A_data_1[4] = { 0x1.1ed34a0000000p-2f, -0x1.57de300000000p-2f, -0x1.1f63a20000000p-6f, 0x1.d59e180000000p-3f };
__global float A_data_2[8] = { -0x1.72b2780000000p-1f, 0x1.0bcc280000000p-2f, -0x1.546bf80000000p+0f, -0x1.67c51c0000000p-3f, 0x1.0f4a9e0000000p-5f, -0x1.c282a80000000p-3f, 0x1.7788400000000p+0f, -0x1.0759a80000000p-5f };
__global float T_matmul_0[4] = { 0.0f, 0.0f, 0.0f, 0.0f };
__global float compgen_host_out_buf[N] = { -0x1.dbf59cp+126f, -0x1.dbf59cp+126f, -0x1.dbf59cp+126f, -0x1.dbf59cp+126f };

int main() {
  {
    compgen_pack_matmul_0_args a = { A_data_2, A_data_0, T_matmul_0 };
    mu_schedule(compgen_pack_matmul_0_callback, &a, 1);
  }
  {
    compgen_pack_add_0_args a = { A_data_1, T_matmul_0, compgen_host_out_buf };
    mu_schedule(compgen_pack_add_0_callback, &a, 1);
  }
  return 0;
}
