PROJECT = writeback_gmem_saturate

VX_SRCS = kernel.cpp

BINFILES := args.bin

OPTS ?= -n64

VORTEX_KN_PATH ?= $(realpath ../../../lib)
GEMMINI_SW_PATH ?= $(realpath ../../../lib/gemmini)

include ../../common.mk
