#!/usr/bin/env python3
"""Generate `data` for the Gemma-2 RMSNorm kernel.

  out[r, :] = x / sqrt(mean(x^2) + eps) * (1.0 + gamma)     eps = 1e-6

Gemma stores the norm weight zero-centered and applies it as (1.0 + weight). fp32,
ROWS=16 x COLS=2304 (real Gemma-2-2b hidden). Golden is numpy fp32 with the same op;
the kernel verifies with an FP tolerance (absorbs rsqrt/reassociation rounding). Emit
helpers come from the shared golden module (lib/golden).
"""
import pathlib
import sys

import numpy as np

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parents[2] / "lib" / "golden"))
import golden as G

HERE = pathlib.Path(__file__).resolve().parent
ROWS, COLS, EPS = 16, 2304, 1.0e-6


def main():
    rng = np.random.default_rng(0x6E6A)
    x = rng.standard_normal((ROWS, COLS)).astype(np.float32)
    gamma = (0.1 * rng.standard_normal(COLS)).astype(np.float32)  # zero-centered
    inv = (1.0 / np.sqrt((x ** 2).mean(axis=1, keepdims=True) + EPS)).astype(np.float32)
    gold = (x * inv * (1.0 + gamma)[None, :]).astype(np.float32)

    with open(HERE / "data", "w") as f:
        f.write("// @generated by gen_data.py -- Gemma-2 RMSNorm (x*rsqrt(mean(x^2)+eps)*(1+gamma))\n")
        f.write("#include <stdint.h>\n")
        f.write(f"#define VERIFY_COUNT {ROWS * COLS}\n")
        f.write(f"static const uint32_t ROWS = {ROWS};\nstatic const uint32_t COLS = {COLS};\n")
        G.emit_f32(f, "x_raw", x, dims=f"[{ROWS * COLS}]", ncol=8)
        G.emit_f32(f, "gamma_raw", gamma, dims=f"[{COLS}]", ncol=8)
        G.emit_f32(f, "out_raw", np.zeros(ROWS * COLS, np.float32), dims=f"[{ROWS * COLS}]", ncol=8)
        G.emit_f32(f, "gold_raw", gold, dims=f"[{ROWS * COLS}]", ncol=8)
        G.emit_f32(f, "tls_guard", np.zeros(1024, np.float32), dims="[1024]", ncol=8)
    print(f"wrote rmsnorm_gemma data ROWS={ROWS} COLS={COLS}")


if __name__ == "__main__":
    main()
