#!/usr/bin/env bash
# Deterministically regenerate every kernel's committed `data` / include/fa_data.h from
# its generator. Run from the repo (or via `make data` in kernels/). Idempotent.
#
# Requirements:
#   * PYTHON with numpy (all generators) and torch (the flash + fused generators).
#     Override the interpreter with:  PYTHON=/path/to/python ./regen_data.sh
#   * the lib/mxgemmini submodule checked out (the flash/fused generators import its
#     Python MX models; run `git submodule update --init lib/mxgemmini` first).
#   * lib/golden/mx_golden is auto-built by the MX generators.
#
# NOTE: kernels/gemm_mxgemmini/mxgemm.data.fp6.*.h is NOT regenerated here. The fp6 gemm
# path is LUT-indexed with an output-LUT requant (C_lut/C_proj_hw) that gen_mxgemm_data.py
# does not model, so that one header stays committed. (The fp6 *mesh* path is otherwise
# exercised + regenerated by kernels/flash_attention_mx_fp6.)
set -euo pipefail
PYTHON="${PYTHON:-python3}"
K="$(cd "$(dirname "$0")" && pwd)"          # kernels/

run() { echo "[regen] $1"; ( cd "$K/$1" && shift && "$PYTHON" "$@" ); }

# --- SIMT op / fused generators (each writes its own `data`), run with no args ---
for d in bias_add layernorm logit_softcap patch_embed geglu \
         rmsnorm_gemma embed_scale gemma_4norm qkv_bias \
         rope_qkv_fused rmsnorm_qkv_fused flash_attention_mx_fp6; do
  run "$d" gen_data.py
done
run simt_quant gen_quant.py

# --- flash attention (fa_gen_data.py -> include/fa_data.h) ---
run flash_attention_mx_gqa   fa_gen_data.py --Sq 64 --Sk 256 --d 64  --block_n 64 \
      --n_q 8 --n_kv 2 --q_pos0 64 --out include/fa_data.h
run flash_attention_mx_gemma fa_gen_data.py --Sq 64 --Sk 256 --d 256 --block_n 64 \
      --n_q 8 --n_kv 4 --q_pos0 64 --window 128 --attn_softcap 50 --out include/fa_data.h

# --- gemm_mxgemmini fp8/fp4 ladder headers ---
run gemm_mxgemmini gen_mxgemm_data.py --all-fp8
run gemm_mxgemmini gen_mxgemm_data.py --all-fp4

# --- weight-stationary / batched-decode `data` = one gen_mxgemm_data.py shape, renamed ---
blob() {  # <dir> <fmt> <M> <N> <K> [gemv]
  local dir="$1" fmt="$2" M="$3" N="$4" Kk="$5" glue="${6:-}"
  echo "[regen] $dir  ($fmt ${M}x${N}x${Kk})"
  ( cd "$K/gemm_mxgemmini" && "$PYTHON" gen_mxgemm_data.py "$fmt" "$M" "$N" "$Kk" >/dev/null )
  cp "$K/gemm_mxgemmini/mxgemm.data.$fmt.m${M}n${N}k${Kk}.h" "$K/$dir/data"
  # The gemv kernels expect the verify glue in `data` (the ws kernels define it in kernel.cpp).
  if [ "$glue" = gemv ]; then
    {
      echo "__global uint16_t C_raw[MATMUL_M*MATMUL_N]={0};"
      echo "static const uint16_t* gold_raw=&C_out_bf16[0][0];"
      echo "#define VERIFY_COUNT (MATMUL_M*MATMUL_N)"
    } >> "$K/$dir/data"
  fi
}
blob gemm_mxgemmini_ws              fp8 256  64 2048
# gemm_mxgemmini_ws_restream: data kept committed (custom A_scales_tiled re-tiling not
# modeled by gen_mxgemm_data.py); see the gitignore exception.
blob gemm_mxgemmini_ws_downproj_fp4 fp4 256  64 5632
blob gemv_batched_fp8_m32           fp8  32 128 2048 gemv
blob gemv_batched_fp8_m64           fp8  64 128 2048 gemv
blob gemv_batched_fp8_m128          fp8 128 128 2048 gemv
blob gemv_batched_fp4_m128          fp4 128 128 2048 gemv

echo "[regen] done."
