// Auto-generated by radiance_muon._host.host_orchestrated_host_cpp.
//
// rv64 host driver for the host-orchestrated execution mode:
//   1. Wait for GPU completion via RAD_HOST_GPU_ALL_FINISHED MMIO.
//   2. Halt GPU (RESET=1) BEFORE the slow HTIF write syscall —
//      otherwise the GPUResetAggregator counts 1000 idle cycles and
//      $finish-es the sim before the write syscall lands. Same idiom
//      as ``kernels/launch/host.cpp`` ("reset before print to
//      prevent simulation end").
//   3. Read N float32 words from HOST_OUT_ADDR — that's the rv64
//      mirror (rad_device_to_host_address) of the GPU's spill buffer
//      symbol's rv32 vaddr.
//   4. Format the entire ``RADIANCE_OUT:<hex>\n`` line into a stack
//      buffer and emit it with **one** ``write(1, …)`` syscall. We
//      avoid stdio printf and per-char loops because each fesvr
//      round-trip (tohost write + fromhost wait) takes O(thousands)
//      of sim cycles; doing 46 of them per run blew past our cycle
//      budget in early prototypes.
//   5. Deassert GPU reset (RESET=0) and spin. The GPU has no active
//      warps post-completion, so ``GPUResetAggregator`` counts 1000
//      idle cycles and $finish-es. We rely on aggregator-driven
//      termination rather than libgloss ``htif_exit(0)`` because
//      RadianceTapeoutSimConfig's testbench acts on the GPU-side
//      tohost path, not the host's.
#include <stdint.h>
#include <unistd.h>
#include <radiance.h>

#define HOST_OUT_ADDR 0x110003200ULL
#define HOST_OUT_N 64

static inline void hex8(char* dst, uint32_t v) {
  static const char hex[] = "0123456789abcdef";
  for (int i = 7; i >= 0; --i) {
    dst[i] = hex[v & 0xF];
    v >>= 4;
  }
}

int main(void) {
  uint32_t finished = 0;
  while (!finished) {
    SYNC_GPU();
    finished = READ_MMIO_32(RAD_HOST_GPU_ALL_FINISHED);
  }
  /* Halt GPU before slow HTIF write syscall; otherwise
   * GPUResetAggregator $finish fires after 1000 idle cycles and
   * pre-empts our write. */
  WRITE_MMIO_32(RAD_HOST_GPU_RESET, 1);
  volatile uint32_t* out = (volatile uint32_t*)HOST_OUT_ADDR;
  static const char prefix[] = "RADIANCE_OUT:";
  enum { PFX = sizeof(prefix) - 1, BODY = 8 * HOST_OUT_N };
  char buf[PFX + BODY + 1];
  for (int i = 0; i < PFX; ++i) buf[i] = prefix[i];
  for (int i = 0; i < HOST_OUT_N; ++i) hex8(&buf[PFX + 8 * i], out[i]);
  buf[PFX + BODY] = '\n';
  write(1, buf, sizeof(buf));
  /* Hand back to the GPU-side aggregator: deassert reset, then spin.
   * No warps are active so the aggregator counts to its idle threshold
   * and triggers $finish. */
  WRITE_MMIO_32(RAD_HOST_GPU_RESET, 0);
  for (;;) { asm volatile ("nop"); }
}
