// Auto-composed by radiance_muon._bundle_kernel from CompGen's
// bundle/generated_kernels/* + payload.mlir + execution_plan.yaml +
// golden_inputs.pt + golden_outputs.pt.
//
// Per-region compute callbacks come from the
// radiance_muon_elementwise provider verbatim. The pack contributes
// data baking, dispatch sequencing, and verification.
#include <mu_intrinsics.h>
#include <mu_schedule.h>
#include <stdint.h>

#define N 64

// ========== region add_0 (op=aten_add) ==========
// Auto-generated by RadianceMuonHandwrittenVecAddProvider.
// region_id  = add_0
// op_family  = add
// arity      = binary
// N          = 64
//
// Compute body lifted verbatim from
//   /scratch2/agustin/radiance-kernels/kernels/vecadd/kernel.cpp
// (only the ``vecadd`` callback — own main, ``VecAddArgs`` struct,
// and ``#include "data"`` are stripped because our composer wraps
// with its standard main + golden-baked input arrays). The stride
// loop ``i = tid; i < n; i += nthreads`` preserves the original's
// multi-warp parallelism so this exercises real SIMT hardware
// rather than the auto-generated scalar fallback.

struct compgen_region_add_0_args {
  __global float* A;
  __global float* B;
  __global float* C;
};

static inline void compgen_region_add_0_compute(
    void* arg,
    uint32_t tid_in_threadblock,
    uint32_t threads_per_threadblock,
    uint32_t /*threadblock_id*/) {
  auto* a = reinterpret_cast<compgen_region_add_0_args*>(arg);
  for (uint32_t i = tid_in_threadblock; i < 64; i += threads_per_threadblock) {
    a->C[i] = a->A[i] + a->B[i];
  }
}

struct compgen_pack_add_0_args {
  __global float* A;
  __global float* B;
  __global float* C;
};

static void compgen_pack_add_0_callback(
    void* arg, uint32_t tid, uint32_t nthreads, uint32_t blk) {
  auto* a = reinterpret_cast<compgen_pack_add_0_args*>(arg);
  compgen_region_add_0_args inner = { a->A, a->B, a->C };
  compgen_region_add_0_compute(&inner, tid, nthreads, blk);
}

__global float A_data_0[64] = { -0x1.d3490a0000000p-2f, -0x1.7843100000000p+0f, -0x1.aef6820000000p-1f, -0x1.0cc8be0000000p+0f, 0x1.437b7e0000000p-3f, 0x1.4ef2d20000000p-2f, -0x1.e1659a0000000p-1f, 0x1.3f53240000000p-1f, 0x1.23ca540000000p-1f, -0x1.149a020000000p-1f, 0x1.3228ea0000000p+0f, 0x1.6b0fe00000000p-3f, 0x1.6d95800000000p-1f, 0x1.0cc8360000000p-8f, 0x1.14c3f40000000p-2f, 0x1.1f6eae0000000p+0f, -0x1.4cb19e0000000p+0f, 0x1.c7dbe20000000p+0f, -0x1.cf02de0000000p-2f, 0x1.4e5d960000000p+0f, 0x1.53aede0000000p+0f, -0x1.1931a40000000p+1f, 0x1.1ed5940000000p+0f, -0x1.fb171a0000000p-1f, -0x1.4539900000000p-1f, 0x1.4aa4440000000p-2f, 0x1.bf6f1e0000000p-4f, -0x1.2b07c00000000p+0f, -0x1.8181f40000000p-6f, 0x1.00a5d20000000p+0f, -0x1.341e3a0000000p-2f, -0x1.f39d960000000p+0f, 0x1.43c59a0000000p+1f, 0x1.b74da40000000p+0f, -0x1.1b21580000000p-2f, -0x1.973df60000000p+0f, -0x1.2adca80000000p+0f, 0x1.0ed1b00000000p+0f, 0x1.caf9320000000p+0f, -0x1.845c2c0000000p-3f, -0x1.0ed2bc0000000p+0f, 0x1.1961e80000000p-1f, -0x1.6663d80000000p-2f, 0x1.e62d0e0000000p-1f, 0x1.486b780000000p-3f, -0x1.70796a0000000p-2f, 0x1.2778140000000p+1f, -0x1.cdacf00000000p-2f, -0x1.4e9b840000000p+0f, 0x1.2858940000000p+1f, -0x1.f9d6860000000p-2f, 0x1.f68c720000000p-1f, 0x1.798aca0000000p+0f, 0x1.5091140000000p+0f, 0x1.c6b93c0000000p-2f, 0x1.3d1ca80000000p-1f, 0x1.b154e20000000p-2f, -0x1.1ea33c0000000p+0f, -0x1.54f5da0000000p-1f, 0x1.b7c9c40000000p-1f, -0x1.a2035c0000000p-2f, -0x1.bb0c5c0000000p+0f, -0x1.6ccd8a0000000p-4f, -0x1.74a6d80000000p-1f };
__global float A_data_1[64] = { 0x1.132f320000000p+0f, -0x1.4f34b20000000p+0f, 0x1.0721860000000p+0f, -0x1.00c03e0000000p-2f, 0x1.9a3cea0000000p-6f, -0x1.a01ae60000000p-2f, 0x1.781b120000000p-1f, -0x1.1b6ef60000000p+0f, 0x1.273bfe0000000p-2f, -0x1.2e01020000000p+1f, -0x1.1fe50c0000000p-1f, 0x1.771a6c0000000p+0f, -0x1.c633320000000p-2f, 0x1.5250d20000000p+0f, 0x1.3720760000000p-2f, -0x1.98adea0000000p-1f, -0x1.6c03660000000p-1f, -0x1.e3a7e40000000p-4f, -0x1.9592f00000000p-3f, 0x1.bbcecc0000000p-1f, 0x1.21fcda0000000p-2f, -0x1.e3302e0000000p-1f, 0x1.fd61360000000p-2f, -0x1.3c97420000000p-1f, -0x1.22a03a0000000p+0f, -0x1.b61aaa0000000p-1f, 0x1.471aa20000000p-1f, 0x1.27c73e0000000p-1f, -0x1.a3b9520000000p+0f, -0x1.3d19da0000000p+0f, 0x1.4b43560000000p-1f, -0x1.14076c0000000p+0f, -0x1.1897140000000p-2f, -0x1.71cbe20000000p-5f, 0x1.2bf9160000000p-1f, -0x1.4a035c0000000p+0f, 0x1.0ec1400000000p-1f, 0x1.7b57080000000p+0f, -0x1.4b93d60000000p+0f, 0x1.155cc80000000p+1f, -0x1.48c0fc0000000p-1f, 0x1.8a445c0000000p-1f, -0x1.4cb37e0000000p+0f, 0x1.8587660000000p-1f, -0x1.8c1cc60000000p+0f, -0x1.b13f820000000p-2f, 0x1.53aef20000000p-1f, 0x1.16f03e0000000p-2f, 0x1.df543c0000000p-1f, -0x1.6702d60000000p+0f, -0x1.cdfb060000000p-4f, 0x1.d060220000000p-6f, -0x1.d76b4a0000000p-2f, -0x1.af0c240000000p-1f, -0x1.e110f80000000p-2f, 0x1.d0fcaa0000000p-1f, -0x1.4f8e420000000p-1f, -0x1.1b765c0000000p+0f, -0x1.753bb40000000p-3f, 0x1.29ee9a0000000p+0f, 0x1.7f45840000000p+0f, 0x1.860f4e0000000p-2f, 0x1.f459bc0000000p+0f, -0x1.d5f4020000000p-2f };
__global float compgen_host_out_buf[N] = { -0x1.dbf59cp+126f, -0x1.dbf59cp+126f, -0x1.dbf59cp+126f, -0x1.dbf59cp+126f, -0x1.dbf59cp+126f, -0x1.dbf59cp+126f, -0x1.dbf59cp+126f, -0x1.dbf59cp+126f, -0x1.dbf59cp+126f, -0x1.dbf59cp+126f, -0x1.dbf59cp+126f, -0x1.dbf59cp+126f, -0x1.dbf59cp+126f, -0x1.dbf59cp+126f, -0x1.dbf59cp+126f, -0x1.dbf59cp+126f, -0x1.dbf59cp+126f, -0x1.dbf59cp+126f, -0x1.dbf59cp+126f, -0x1.dbf59cp+126f, -0x1.dbf59cp+126f, -0x1.dbf59cp+126f, -0x1.dbf59cp+126f, -0x1.dbf59cp+126f, -0x1.dbf59cp+126f, -0x1.dbf59cp+126f, -0x1.dbf59cp+126f, -0x1.dbf59cp+126f, -0x1.dbf59cp+126f, -0x1.dbf59cp+126f, -0x1.dbf59cp+126f, -0x1.dbf59cp+126f, -0x1.dbf59cp+126f, -0x1.dbf59cp+126f, -0x1.dbf59cp+126f, -0x1.dbf59cp+126f, -0x1.dbf59cp+126f, -0x1.dbf59cp+126f, -0x1.dbf59cp+126f, -0x1.dbf59cp+126f, -0x1.dbf59cp+126f, -0x1.dbf59cp+126f, -0x1.dbf59cp+126f, -0x1.dbf59cp+126f, -0x1.dbf59cp+126f, -0x1.dbf59cp+126f, -0x1.dbf59cp+126f, -0x1.dbf59cp+126f, -0x1.dbf59cp+126f, -0x1.dbf59cp+126f, -0x1.dbf59cp+126f, -0x1.dbf59cp+126f, -0x1.dbf59cp+126f, -0x1.dbf59cp+126f, -0x1.dbf59cp+126f, -0x1.dbf59cp+126f, -0x1.dbf59cp+126f, -0x1.dbf59cp+126f, -0x1.dbf59cp+126f, -0x1.dbf59cp+126f, -0x1.dbf59cp+126f, -0x1.dbf59cp+126f, -0x1.dbf59cp+126f, -0x1.dbf59cp+126f };

int main() {
  {
    compgen_pack_add_0_args a = { A_data_0, A_data_1, compgen_host_out_buf };
    mu_schedule(compgen_pack_add_0_callback, &a, 4);
  }
  return 0;
}
