// Auto-composed by radiance_muon._bundle_kernel from CompGen's
// bundle/generated_kernels/* + payload.mlir + execution_plan.yaml +
// golden_inputs.pt + golden_outputs.pt.
//
// Per-region compute callbacks come from the
// radiance_muon_elementwise provider verbatim. The pack contributes
// data baking, dispatch sequencing, and verification.
#include <mu_intrinsics.h>
#include <mu_schedule.h>
#include <stdint.h>

#define N 4

// ========== region matmul_0 (op=linalg.matmul) ==========
// Auto-generated by RadianceMuonMatmulProvider.
// region_id = matmul_0
// op_family = matmul
// M         = 1
// K         = 8
// N         = 4
//
// Compute-only emit. The pack's composer wraps this with includes,
// data arrays (M*K + K*N flat float32 init), an MxN output buffer,
// dispatch sequencing, and verification against the model's golden.

struct compgen_region_matmul_0_args {
  __global float* A;   // M*K row-major
  __global float* B;   // K*N row-major
  __global float* C;   // M*N row-major
};

static inline void compgen_region_matmul_0_compute(
    void* arg, uint32_t tid, uint32_t /*nthreads*/, uint32_t /*blk*/) {
  if (tid != 0) return;
  auto* a = reinterpret_cast<compgen_region_matmul_0_args*>(arg);
  for (uint32_t m = 0; m < 1; ++m) {
    for (uint32_t n = 0; n < 4; ++n) {
      float acc = 0.0f;
      for (uint32_t k = 0; k < 8; ++k) {
        acc += a->A[m * 8 + k] * a->B[k * 4 + n];
      }
      a->C[m * 4 + n] = acc;
    }
  }
}

// ========== region add_0 (op=aten_bias_add) ==========
// Auto-generated by RadianceMuonBiasAddProvider.
// region_id  = add_0
// op_family  = bias_add
// arity      = binary
// N          = 4
// bias_len   = 4
//
// Compute-only emit. The pack composer wraps with main + data + dispatch.
// A: bias vector (length 4)
// B: input matrix (flattened length 4, row-major rows of 4)
// C: output matrix (flattened length 4)
// C[i] = B[i] + A[i % bias_len]

struct compgen_region_add_0_args {
  __global float* A;   // bias, length 4
  __global float* B;   // input matrix, flat length 4
  __global float* C;   // output matrix, flat length 4
};

static inline void compgen_region_add_0_compute(
    void* arg, uint32_t /*tid*/, uint32_t /*nthreads*/, uint32_t /*blk*/) {
  auto* a = reinterpret_cast<compgen_region_add_0_args*>(arg);
  for (uint32_t i = 0; i < 4; ++i) {
    a->C[i] = a->B[i] + a->A[i % 4];
  }
}

struct compgen_pack_matmul_0_args {
  __global float* A;
  __global float* B;
  __global float* C;
};

static void compgen_pack_matmul_0_callback(
    void* arg, uint32_t tid, uint32_t nthreads, uint32_t blk) {
  auto* a = reinterpret_cast<compgen_pack_matmul_0_args*>(arg);
  compgen_region_matmul_0_args inner = { a->A, a->B, a->C };
  compgen_region_matmul_0_compute(&inner, tid, nthreads, blk);
}

struct compgen_pack_add_0_args {
  __global float* A;
  __global float* B;
  __global float* C;
};

static void compgen_pack_add_0_callback(
    void* arg, uint32_t tid, uint32_t nthreads, uint32_t blk) {
  auto* a = reinterpret_cast<compgen_pack_add_0_args*>(arg);
  compgen_region_add_0_args inner = { a->A, a->B, a->C };
  compgen_region_add_0_compute(&inner, tid, nthreads, blk);
}

struct compgen_pack_verify_args {
  __global float* C;
  __global float* EXP;
  __global volatile uint32_t* mismatch;
};

static void compgen_pack_verify_kernel(
    void* arg, uint32_t tid, uint32_t /*nthreads*/, uint32_t /*blk*/) {
  auto* a = reinterpret_cast<compgen_pack_verify_args*>(arg);
  if (tid != 0) return;
  // Accumulate any-mismatch via XOR-OR rather than per-iteration
  // ``if`` checks — at moderate N (≥32) the per-iteration branch
  // form pushes onto Muon's ipdom (immediate post-dominator) stack
  // without timely pops and the sim asserts ``ipdom stack is full``.
  // Branch-free accumulation keeps the loop body straight-line.
  uint32_t mismatch_bits = 0u;
  for (uint32_t i = 0; i < 4; ++i) {
    uint32_t got = __builtin_bit_cast(uint32_t, a->C[i]);
    uint32_t exp = __builtin_bit_cast(uint32_t, a->EXP[i]);
    mismatch_bits |= (got ^ exp);
  }
  if (mismatch_bits != 0u) {
    *a->mismatch = 0xDEADBEEFu;
    for (;;) { /* never go idle — sim cycle-budget will fire */ }
  }
}

__global float A_data_0[32] = { 0x1.28b0380000000p-3f, -0x1.583d2e0000000p-2f, 0x1.4551140000000p-2f, -0x1.6ab4880000000p-3f, 0x1.58ded00000000p-2f, 0x1.e9c6a60000000p-3f, -0x1.399b6c0000000p-2f, -0x1.0b53b80000000p-2f, 0x1.542ca20000000p-2f, 0x1.5eebde0000000p-2f, 0x1.001ce00000000p-2f, 0x1.c07cb40000000p-3f, -0x1.7aaad00000000p-3f, 0x1.8e0d780000000p-4f, -0x1.58b6d00000000p-2f, 0x1.3886f80000000p-3f, 0x1.5c36680000000p-3f, 0x1.c9724c0000000p-4f, 0x1.6614600000000p-2f, 0x1.66c6d00000000p-2f, -0x1.260c1c0000000p-6f, -0x1.8bf1320000000p-3f, -0x1.407fb00000000p-2f, 0x1.8d66f60000000p-3f, 0x1.5156e80000000p-3f, -0x1.1ed59c0000000p-2f, 0x1.19c2ba0000000p-3f, -0x1.f9faea0000000p-4f, -0x1.35d06c0000000p-2f, -0x1.3372080000000p-2f, -0x1.d6a9880000000p-3f, -0x1.9878020000000p-4f };
__global float A_data_1[4] = { -0x1.aabb940000000p-5f, 0x1.92d59a0000000p-3f, 0x1.28c47a0000000p-4f, -0x1.ace8a40000000p-3f };
__global float A_data_2[8] = { -0x1.152a240000000p+0f, -0x1.4aba420000000p+0f, 0x1.c53c880000000p+0f, -0x1.d7cecc0000000p-1f, 0x1.58dce20000000p-1f, 0x1.ef186e0000000p+0f, -0x1.47d6be0000000p-3f, 0x1.e0e7580000000p+0f };
__global float T_matmul_0[4] = { 0.0f, 0.0f, 0.0f, 0.0f };
__global float T_add_0[4] = { 0.0f, 0.0f, 0.0f, 0.0f };
__global float EXP_data[N] = { -0x1.9a05ac0000000p-2f, -0x1.9117f80000000p-5f, 0x1.b791f40000000p-5f, 0x1.02a8160000000p+0f };
__global volatile uint32_t mismatch_flag = 0u;

int main() {
  {
    compgen_pack_matmul_0_args a = { A_data_2, A_data_0, T_matmul_0 };
    mu_schedule(compgen_pack_matmul_0_callback, &a, 1);
  }
  {
    compgen_pack_add_0_args a = { A_data_1, T_matmul_0, T_add_0 };
    mu_schedule(compgen_pack_add_0_callback, &a, 1);
  }
  {
    compgen_pack_verify_args a = { T_add_0, EXP_data, &mismatch_flag };
    mu_schedule(compgen_pack_verify_kernel, &a, 1);
  }
  return 0;
}
