#!/usr/bin/env python3
"""Gemma-2 FINAL-logit soft-capping golden: OUT = cap * tanh(logits / cap), cap = 30.0.

Confirmed from google/gemma-2-2b-it config.json: "final_logit_softcapping": 30.0. This is a
plain SIMT elementwise epilogue on the LM-head output (applied to the [seq, vocab] logits
just before the softmax over the vocabulary). We test a [rows, cols] tile with logit values
that span into the tanh-saturating regime (|x| >> cap) so the cap is actually exercised
(not a near-linear no-op): x ~ N(0, 45^2) reaches |x| ~ 120 = 4*cap.

Golden uses fp64 tanh; the kernel uses a fp32 exp-based tanh (expf_/tanhf_ in kernel.cpp).
The soft-cap reference and emit come from the shared golden module (lib/golden).
"""
import pathlib
import sys

import numpy as np

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parents[2] / "lib" / "golden"))
import golden as G

R, Cc = 64, 512
CAP = np.float64(30.0)
rng = np.random.default_rng(2)
# wide spread so many entries saturate tanh -> the cap genuinely compresses them
X = (np.float32(45.0) * rng.standard_normal((R, Cc), dtype=np.float32)).astype(np.float32)
gold = G.softcap(X, CAP)

with open("data", "w") as f:
    f.write("// generated by gen_data.py - do not edit\n")
    f.write(f"#define VERIFY_COUNT {R*Cc}\n")
    f.write(f"static const uint32_t ROWS = {R};\nstatic const uint32_t COLS = {Cc};\n")
    f.write(f"static const float FINAL_SOFTCAP = 30.0f;\n")
    G.emit_f32(f, "x_raw", X)
    G.emit_f32(f, "out_raw", np.zeros((R, Cc), np.float32))
    G.emit_f32(f, "gold_raw", gold)
    f.write("__global float tls_guard[1024] = {0};\n")

frac_sat = float(np.mean(np.abs(X) > CAP))
print(f"wrote data: final softcap {R}x{Cc}  cap={float(CAP)}  "
      f"|x|>cap fraction={frac_sat:.2f}  x range=[{X.min():.1f},{X.max():.1f}]  "
      f"gold range=[{gold.min():.3f},{gold.max():.3f}]")
