#!/usr/bin/env python3
"""Emit the OUTPUT-PROJECTION operand and golden as a C header, additive to fa_data.h.

Step 1 of workspace-notes/FA_PROJECTION_PLAN.md: Y[Sq][dm] = O[Sq][d] @ Wo[d][dm].

Additive on purpose.  fa_data.h holds the Q/K/V the attention is already verified against, and
regenerating it would re-baseline every golden; this header only ADDS Wo and the Y golden, so the
attention result stays exactly what the boards produced.  The later QKV-projection steps do need
Q/K/V redefined as projection outputs, and that is where a new data header and a re-baseline come in.

The GEMM contracts over d, so B = Wo[d][dm] is grouped along d:
  OP_B_in[d][dm]              fp8 e4m3
  OP_B_scales_col[d/32][dm]   E8M0
A = O is produced at runtime and requantized in the kernel, so it has no static operand here.

Usage: python3 gen_proj_data.py --Sq 64 --Sk 256 --d 128 --dm 128 --seed 0 --out include/fa_proj_data.h
"""
import argparse, os, sys
LIB = "/scratch/yrh/radiance-kernels/lib/mxgemmini"
sys.path.insert(0, LIB)
import torch
import fp8_matmul_model as G
import flash_attention_model as FA

INPUT_SPEC, SCALE_SPEC, GROUP = G.INPUT_SPEC, G.SCALE_SPEC, G.GROUP

def fmt_rows(hex_rows):
    return ",\n".join("    { " + ", ".join(f"0x{h}" for h in row) + " }" for row in hex_rows)

def emit_fp8(f, name, mat, dims):
    codes, bits = G.tensor_to_custom_fp_codes(mat, INPUT_SPEC)
    f.write(f"static const {G.c_type_for_bits(bits)} {name}{dims} = {{\n{fmt_rows(G.codes_to_hex_rows(codes, bits))}\n}};\n\n")

def emit_scale(f, name, mat, dims):
    codes, bits = G.tensor_to_custom_fp_codes(mat, SCALE_SPEC)
    bits -= 1                      # E8M0: drop the sign bit, keep the 8 exponent bits
    f.write(f"static const {G.c_type_for_bits(bits)} {name}{dims} = {{\n{fmt_rows(G.codes_to_hex_rows(codes, bits))}\n}};\n\n")

def emit_bf16(f, name, mat, dims):
    codes, bits = G.tensor_to_custom_fp_codes(mat, "bf16")
    f.write(f"static const uint16_t {name}{dims} = {{\n{fmt_rows(G.codes_to_hex_rows(codes, bits))}\n}};\n\n")

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--Sq", type=int, default=64)
    ap.add_argument("--Sk", type=int, default=256)
    ap.add_argument("--d", type=int, default=128)
    ap.add_argument("--dm", type=int, default=128)
    ap.add_argument("--seed", type=int, default=0)
    ap.add_argument("--wseed", type=int, default=1234)
    ap.add_argument("--out", type=str, default="include/fa_proj_data.h")
    args = ap.parse_args()
    Sq, Sk, d, dm = args.Sq, args.Sk, args.d, args.dm
    assert d % GROUP == 0 and dm % GROUP == 0

    # Reproduce the attention exactly as gen_data.py did, to get the O the projection consumes.
    softmax_scale = 1.0 / (d ** 0.5)
    Q, K, V = FA.make_inputs(Sq, Sk, d, args.seed, peaked=False)
    O_mx = FA.mx_attention_dense(Q, K, V, softmax_scale)

    gw = torch.Generator().manual_seed(args.wseed)
    Wo = torch.randn(d, dm, generator=gw) / (d ** 0.5)

    # B operand grouped along the contraction dim d: quantize Wo^T along its last dim, then
    # transpose back into [d][dm] / [d/32][dm].
    Wo_fp8_t, Wo_scales_t = FA.mx_quantize_cols(Wo.t().contiguous())    # [dm,d], [dm,d/32]
    OP_B_in = Wo_fp8_t.t().contiguous()                                  # [d][dm]
    OP_B_scales_col = Wo_scales_t.t().contiguous()                       # [d/32][dm]

    Y_mx = FA.mx_matmul(O_mx, Wo)          # what the mesh should produce
    Y_ref = O_mx.float() @ Wo.float()      # fp32 reference, for context only

    out = args.out
    os.makedirs(os.path.dirname(out) or ".", exist_ok=True)
    with open(out, "w") as f:
        f.write("#ifndef FA_PROJ_DATA_H\n#define FA_PROJ_DATA_H\n\n#include <stdint.h>\n\n")
        f.write(f"// Output projection Y[{Sq}][{dm}] = O[{Sq}][{d}] @ Wo[{d}][{dm}], contract over d.\n")
        f.write(f"// Generated by gen_proj_data.py, attention seed {args.seed}, weight seed {args.wseed}.\n\n")
        f.write(f"#define FA_DM {dm}\n\n")
        emit_fp8(f, "OP_B_in", OP_B_in, "[FA_D][FA_DM]")
        emit_scale(f, "OP_B_scales_col", OP_B_scales_col, "[FA_GK][FA_DM]")
        f.write("// golden mesh output projection (bf16)\n")
        emit_bf16(f, "Y_mx_bf16", Y_mx, "[FA_SQ][FA_DM]")
        f.write("// fp32 reference, for context\n")
        emit_bf16(f, "Y_ref_bf16", Y_ref, "[FA_SQ][FA_DM]")
        f.write("#endif // FA_PROJ_DATA_H\n")

    rel = (Y_mx - Y_ref).norm().item() / Y_ref.norm().item()
    print(f"wrote {out}  Sq={Sq} d={d} dm={dm}  MX-vs-fp32 rel err = {rel:.3e}")
    print(f"  O_mx range [{O_mx.min():.4f},{O_mx.max():.4f}]  Y_mx range [{Y_mx.min():.4f},{Y_mx.max():.4f}]")

if __name__ == "__main__":
    main()
