#!/usr/bin/env python3
"""MX-fp8 (e4m3) block quantization coverage kernel data.

Input: bf16 activation tile X[M][N] (M=64, N=512), stored as fp32 holding
bf16-exact values.  For each contiguous 32-element block along N:
    amax  = max |x| in block
    e     = ceil(log2(amax / FP8_MAX))          (FP8_MAX = 448.0)
    scale = 2^e,  e8m0 code = e + 127 (clamped [0,254])
    out_fp8[i] = quantize_e4m3(x[i] * 2^-e)      (round-to-nearest-even)

The bit primitives (fp8_code_rshift, block_exp, pow2_neg_e, round_bf16_bits) come from
the shared golden module (lib/golden) and mirror the device kernel's exact integer/float
ops, so the golden is bit-exact with the kernel output.  Outputs are packed
little-endian: 4 fp8 codes per uint32 word; one e8m0 code per uint32.
"""
import pathlib
import sys

import numpy as np

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parents[2] / "lib" / "golden"))
import golden as G

HERE = pathlib.Path(__file__).resolve().parent
M, N = 64, 512
BLK = 32
NBLK_ROW = N // BLK            # 16
NUM_BLOCKS = M * NBLK_ROW      # 1024
FP8_MAX = 448.0

# ---- generate bf16 inputs -------------------------------------------------
rng = np.random.default_rng(1234)
X = rng.standard_normal((M, N)).astype(np.float32)
X = np.tanh(X).astype(np.float32)
# give each 32-block its own magnitude so the per-block scale, subnormal, and
# near-saturation paths all get exercised (block amax spans ~2^-6 .. ~2^6).
mag_exps = rng.integers(-6, 7, size=(M, NBLK_ROW)).astype(np.float32)
mag = np.power(np.float32(2.0), mag_exps).astype(np.float32)      # per block
mag = np.repeat(mag, BLK, axis=1).astype(np.float32)             # broadcast to elems
X = (X * mag).astype(np.float32)
# round every element to bf16 (stored back as fp32)
Xb = np.empty_like(X)
flatX = X.reshape(-1)
flatXb = Xb.reshape(-1)
for i in range(flatX.size):
    flatXb[i] = G.bits_f32(G.round_bf16_bits(G.f32_bits(flatX[i])))

# ---- reference quantization ----------------------------------------------
codes = np.zeros(M * N, dtype=np.uint8)
scale_codes = np.zeros(NUM_BLOCKS, dtype=np.uint8)
for b in range(NUM_BLOCKS):
    base = b * BLK
    blk = flatXb[base:base + BLK]
    amax = np.float32(0.0)
    for v in blk:
        av = np.float32(abs(v))
        if av > amax:
            amax = av
    if float(amax) == 0.0:
        scale_codes[b] = 0
        # codes already 0
        continue
    e = G.block_exp(G.f32_bits(amax))
    sc = e + 127
    sc = 0 if sc < 0 else (254 if sc > 254 else sc)
    scale_codes[b] = sc
    p2 = G.pow2_neg_e(e)
    for j in range(BLK):
        xs = np.float32(np.float32(blk[j]) * np.float32(p2))
        codes[base + j] = G.fp8_code_rshift(xs)

# pack 4 fp8 codes / uint32 word, little-endian element order
packed = np.zeros(M * N // 4, dtype=np.uint32)
for w in range(packed.size):
    packed[w] = (int(codes[4 * w + 0])
                 | (int(codes[4 * w + 1]) << 8)
                 | (int(codes[4 * w + 2]) << 16)
                 | (int(codes[4 * w + 3]) << 24))
scales32 = scale_codes.astype(np.uint32)

# ---- emit -----------------------------------------------------------------
with open(HERE / "data", "w") as f:
    f.write("// generated by gen_quant.py - do not edit\n")
    f.write("// MX-fp8 (e4m3) per-32-block quantization of a bf16 activation tile\n")
    f.write(f"static const uint32_t M = {M};\n")
    f.write(f"static const uint32_t N = {N};\n")
    f.write(f"static const uint32_t BLK = {BLK};\n")
    f.write(f"static const uint32_t NUM_BLOCKS = {NUM_BLOCKS};\n")
    f.write(f"#define PACKED_COUNT {M*N//4}\n")
    f.write(f"#define SCALE_COUNT {NUM_BLOCKS}\n")
    # single contiguous golden: packed fp8 words first, then e8m0 scale words.
    # keeps verify() to one tight loop over two arrays -> fewer distinct
    # registers on the main()-running warps (rename-budget headroom).
    gold_all = np.concatenate([packed, scales32]).astype(np.uint32)
    f.write(f"#define TOTAL_COUNT {gold_all.size}\n")
    G.emit_f32(f, "X_raw", Xb)
    G.emit_u32(f, "gold_all", gold_all)

# quick sanity print
nz = int((codes != 0).sum())
print(f"wrote {HERE / 'data'}")
print(f"blocks={NUM_BLOCKS} elems={M*N} nonzero_fp8={nz} "
      f"scale_min={int(scale_codes.min())} scale_max={int(scale_codes.max())}")
print("sample codes[:8]=", [int(c) for c in codes[:8]])
print("sample scale[:4]=", [int(c) for c in scale_codes[:4]])
