// Auto-composed by radiance_muon._bundle_kernel from CompGen's
// bundle/generated_kernels/* + payload.mlir + execution_plan.yaml +
// golden_inputs.pt + golden_outputs.pt.
//
// Per-region compute callbacks come from the
// radiance_muon_elementwise provider verbatim. The pack contributes
// data baking, dispatch sequencing, and verification.
#include <mu_intrinsics.h>
#include <mu_schedule.h>
#include <stdint.h>

#define N 4

// ========== region add_0 (op=aten_add) ==========
// Auto-generated by RadianceMuonElementwiseProvider.
// region_id = add_0
// op_family = add
// arity     = binary
// N         = 4
//
// Compute-only emit. The pack's composer wraps this with includes,
// data arrays, intermediate buffers, dispatch sequencing in
// execution_order, and a final on-GPU bit-compare against the model's
// expected output.
//
// Stride loop ``i = tid; i += nthreads`` is **load-bearing**: a
// scalar single-thread emit (or even ``tid == 0`` gate) blows up
// Muon's ipdom (immediate post-dominator) stack at N ≥ ~32 when
// combined with the verify kernel's per-element check. Striding
// across lanes keeps each lane's iteration count and divergence
// shallow enough to fit. relu's branch-free ``__builtin_fmaxf``
// keeps the per-element op divergence-free.

struct compgen_region_add_0_args {
  __global float* A;
  __global float* B;
  __global float* C;
};

static inline void compgen_region_add_0_compute(
    void* arg, uint32_t tid, uint32_t nthreads, uint32_t /*blk*/) {
  auto* a = reinterpret_cast<compgen_region_add_0_args*>(arg);
  for (uint32_t i = tid; i < 4; i += nthreads) {
    a->C[i] = a->A[i] + a->B[i];
  }
}

// ========== region relu_relu (op=aten_relu_default) ==========
// Auto-generated by RadianceMuonElementwiseProvider.
// region_id = relu_relu
// op_family = relu
// arity     = unary
// N         = 4
//
// Compute-only emit. The pack's composer wraps this with includes,
// data arrays, intermediate buffers, dispatch sequencing in
// execution_order, and a final on-GPU bit-compare against the model's
// expected output.
//
// Stride loop ``i = tid; i += nthreads`` is **load-bearing**: a
// scalar single-thread emit (or even ``tid == 0`` gate) blows up
// Muon's ipdom (immediate post-dominator) stack at N ≥ ~32 when
// combined with the verify kernel's per-element check. Striding
// across lanes keeps each lane's iteration count and divergence
// shallow enough to fit. relu's branch-free ``__builtin_fmaxf``
// keeps the per-element op divergence-free.

struct compgen_region_relu_relu_args {
  __global float* A;
  __global float* C;
};

static inline void compgen_region_relu_relu_compute(
    void* arg, uint32_t tid, uint32_t nthreads, uint32_t /*blk*/) {
  auto* a = reinterpret_cast<compgen_region_relu_relu_args*>(arg);
  for (uint32_t i = tid; i < 4; i += nthreads) {
    a->C[i] = __builtin_fmaxf(a->A[i], 0.0f);
  }
}

struct compgen_pack_add_0_args {
  __global float* A;
  __global float* B;
  __global float* C;
};

static void compgen_pack_add_0_callback(
    void* arg, uint32_t tid, uint32_t nthreads, uint32_t blk) {
  auto* a = reinterpret_cast<compgen_pack_add_0_args*>(arg);
  compgen_region_add_0_args inner = { a->A, a->B, a->C };
  compgen_region_add_0_compute(&inner, tid, nthreads, blk);
}

struct compgen_pack_relu_relu_args {
  __global float* A;
  __global float* C;
};

static void compgen_pack_relu_relu_callback(
    void* arg, uint32_t tid, uint32_t nthreads, uint32_t blk) {
  auto* a = reinterpret_cast<compgen_pack_relu_relu_args*>(arg);
  compgen_region_relu_relu_args inner = { a->A, a->C };
  compgen_region_relu_relu_compute(&inner, tid, nthreads, blk);
}

struct compgen_pack_verify_args {
  __global float* C;
  __global float* EXP;
  __global volatile uint32_t* mismatch;
};

static void compgen_pack_verify_kernel(
    void* arg, uint32_t tid, uint32_t /*nthreads*/, uint32_t /*blk*/) {
  auto* a = reinterpret_cast<compgen_pack_verify_args*>(arg);
  if (tid != 0) return;
  // Accumulate any-mismatch via XOR-OR rather than per-iteration
  // ``if`` checks — at moderate N (≥32) the per-iteration branch
  // form pushes onto Muon's ipdom (immediate post-dominator) stack
  // without timely pops and the sim asserts ``ipdom stack is full``.
  // Branch-free accumulation keeps the loop body straight-line.
  uint32_t mismatch_bits = 0u;
  for (uint32_t i = 0; i < 4; ++i) {
    uint32_t got = __builtin_bit_cast(uint32_t, a->C[i]);
    uint32_t exp = __builtin_bit_cast(uint32_t, a->EXP[i]);
    mismatch_bits |= (got ^ exp);
  }
  if (mismatch_bits != 0u) {
    *a->mismatch = 0xDEADBEEFu;
    for (;;) { /* never go idle — sim cycle-budget will fire */ }
  }
}

__global float A_data_0[4] = { -0x1.b35e400000000p-2f, 0x1.b8bba60000000p+0f, 0x1.6faff80000000p-4f, -0x1.ec7aa00000000p-2f };
__global float A_data_1[4] = { -0x1.0a2c0a0000000p+0f, -0x1.42a6fc0000000p+0f, 0x1.7822b00000000p-1f, -0x1.07dc6e0000000p-2f };
__global float T_add_0[4] = { 0.0f, 0.0f, 0.0f, 0.0f };
__global float T_relu_relu[4] = { 0.0f, 0.0f, 0.0f, 0.0f };
__global float EXP_data[N] = { 0x0.0p+0f, 0x1.d852a80000000p-2f, 0x1.a618b00000000p-1f, 0x0.0p+0f };
__global volatile uint32_t mismatch_flag = 0u;

int main() {
  {
    compgen_pack_add_0_args a = { A_data_0, A_data_1, T_add_0 };
    mu_schedule(compgen_pack_add_0_callback, &a, 1);
  }
  {
    compgen_pack_relu_relu_args a = { T_add_0, T_relu_relu };
    mu_schedule(compgen_pack_relu_relu_callback, &a, 1);
  }
  {
    compgen_pack_verify_args a = { T_relu_relu, EXP_data, &mismatch_flag };
    mu_schedule(compgen_pack_verify_kernel, &a, 1);
  }
  return 0;
}
