"""nightly_data.py: helpers for the nightly kernels' data generators.

A generator lays tensors out in up to four region blobs (see lib/linker/mu_link_nightly.ld:
region1 = device 0x2000_0000, region2 = 0x4000_0000, region3 = 0x6000_0000; region0 lands after
.rodata at a link-time address and is therefore not used for fixed offsets), writes one
<name>.regionN.bin per region, and one C header with the device address and size of every
tensor.  The host and the device both include that header.
"""
import os
import numpy as np

REGION_BASE = {1: 0x20000000, 2: 0x40000000, 3: 0x60000000}


def bf16_bits(x):
    """float array -> uint16 bf16 codes, round to nearest even."""
    f = np.ascontiguousarray(np.asarray(x, dtype=np.float32))
    u = f.view(np.uint32).astype(np.uint64)
    rounded = (u + 0x7FFF + ((u >> 16) & 1)) >> 16
    out = rounded.astype(np.uint16)
    nan = np.isnan(f)
    out[nan] = 0x7FC0
    return out


def bf16_to_f32(b):
    return (np.asarray(b, dtype=np.uint32) << 16).view(np.float32)


class Layout:
    """Accumulates tensors into region blobs with 256-byte alignment."""

    def __init__(self, name, align=256):
        self.name = name
        self.align = align
        self.blobs = {}      # region -> bytearray
        self.defs = []       # (macro, value, comment)

    def add(self, sym, region, array, comment=""):
        data = np.ascontiguousarray(array).tobytes()
        blob = self.blobs.setdefault(region, bytearray())
        pad = (-len(blob)) % self.align
        blob.extend(b"\0" * pad)
        off = len(blob)
        blob.extend(data)
        addr = REGION_BASE[region] + off
        self.defs.append((f"{sym}_ADDR", f"0x{addr:08x}u", comment))
        self.defs.append((f"{sym}_BYTES", f"{len(data)}u", ""))
        return addr

    def reserve(self, sym, region, nbytes, fill=0, comment=""):
        return self.add(sym, region, np.full(nbytes, fill, dtype=np.uint8), comment)

    def const(self, sym, value, comment=""):
        self.defs.append((sym, str(value), comment))

    def write(self, outdir, header):
        os.makedirs(outdir, exist_ok=True)
        paths = []
        for region, blob in sorted(self.blobs.items()):
            p = os.path.join(outdir, f"{self.name}.region{region}.bin")
            with open(p, "wb") as f:
                f.write(bytes(blob))
            paths.append(p)
        guard = os.path.basename(header).upper().replace(".", "_")
        with open(header, "w") as f:
            f.write(f"// generated by the {self.name} data generator; do not edit\n")
            f.write(f"#ifndef {guard}\n#define {guard}\n")
            for m, v, c in self.defs:
                f.write(f"#define {m} {v}" + (f"  // {c}" if c else "") + "\n")
            f.write("#endif\n")
        return paths
