// Auto-composed by radiance_muon._bundle_kernel from CompGen's
// bundle/generated_kernels/* + payload.mlir + execution_plan.yaml +
// golden_inputs.pt + golden_outputs.pt.
//
// Per-region compute callbacks come from the
// radiance_muon_elementwise provider verbatim. The pack contributes
// data baking, dispatch sequencing, and verification.
#include <mu_intrinsics.h>
#include <mu_schedule.h>
#include <stdint.h>

#define N 64

// ========== region add_0 (op=aten_add) ==========
// Auto-generated by RadianceMuonHandwrittenVecAddProvider.
// region_id  = add_0
// op_family  = add
// arity      = binary
// N          = 64
//
// Compute body lifted verbatim from
//   /scratch2/agustin/radiance-kernels/kernels/vecadd/kernel.cpp
// (only the ``vecadd`` callback — own main, ``VecAddArgs`` struct,
// and ``#include "data"`` are stripped because our composer wraps
// with its standard main + golden-baked input arrays). The stride
// loop ``i = tid; i < n; i += nthreads`` preserves the original's
// multi-warp parallelism so this exercises real SIMT hardware
// rather than the auto-generated scalar fallback.

struct compgen_region_add_0_args {
  __global float* A;
  __global float* B;
  __global float* C;
};

static inline void compgen_region_add_0_compute(
    void* arg,
    uint32_t tid_in_threadblock,
    uint32_t threads_per_threadblock,
    uint32_t /*threadblock_id*/) {
  auto* a = reinterpret_cast<compgen_region_add_0_args*>(arg);
  for (uint32_t i = tid_in_threadblock; i < 64; i += threads_per_threadblock) {
    a->C[i] = a->A[i] + a->B[i];
  }
}

struct compgen_pack_add_0_args {
  __global float* A;
  __global float* B;
  __global float* C;
};

static void compgen_pack_add_0_callback(
    void* arg, uint32_t tid, uint32_t nthreads, uint32_t blk) {
  auto* a = reinterpret_cast<compgen_pack_add_0_args*>(arg);
  compgen_region_add_0_args inner = { a->A, a->B, a->C };
  compgen_region_add_0_compute(&inner, tid, nthreads, blk);
}

struct compgen_pack_verify_args {
  __global float* C;
  __global float* EXP;
  __global volatile uint32_t* mismatch;
};

static void compgen_pack_verify_kernel(
    void* arg, uint32_t tid, uint32_t /*nthreads*/, uint32_t /*blk*/) {
  auto* a = reinterpret_cast<compgen_pack_verify_args*>(arg);
  if (tid != 0) return;
  // Accumulate any-mismatch via XOR-OR rather than per-iteration
  // ``if`` checks — at moderate N (≥32) the per-iteration branch
  // form pushes onto Muon's ipdom (immediate post-dominator) stack
  // without timely pops and the sim asserts ``ipdom stack is full``.
  // Branch-free accumulation keeps the loop body straight-line.
  uint32_t mismatch_bits = 0u;
  for (uint32_t i = 0; i < 64; ++i) {
    uint32_t got = __builtin_bit_cast(uint32_t, a->C[i]);
    uint32_t exp = __builtin_bit_cast(uint32_t, a->EXP[i]);
    mismatch_bits |= (got ^ exp);
  }
  if (mismatch_bits != 0u) {
    *a->mismatch = 0xDEADBEEFu;
    for (;;) { /* never go idle — sim cycle-budget will fire */ }
  }
}

__global float A_data_0[64] = { 0x1.1158760000000p-4f, 0x1.0958b00000000p-1f, -0x1.3e27b20000000p-2f, -0x1.d427040000000p+0f, 0x1.5a62d00000000p-3f, 0x1.37b0120000000p-2f, -0x1.2fa2640000000p+0f, -0x1.9fa2060000000p+0f, 0x1.3fec6a0000000p-1f, -0x1.293fa40000000p+0f, 0x1.6282240000000p-1f, 0x1.5745cc0000000p-4f, -0x1.bde02c0000000p-3f, -0x1.2c9a420000000p-2f, 0x1.4916340000000p-2f, -0x1.5d0f9a0000000p+0f, 0x1.5bf84a0000000p-3f, -0x1.2127680000000p-2f, -0x1.054adc0000000p+1f, -0x1.0625d40000000p+1f, 0x1.5badd80000000p+0f, 0x1.f269060000000p+0f, 0x1.cb01d20000000p-4f, -0x1.ec52100000000p-4f, -0x1.6c1b160000000p+0f, -0x1.9b192c0000000p-1f, 0x1.d2ffbe0000000p-9f, 0x1.15112a0000000p-2f, -0x1.e4fee60000000p-1f, 0x1.47ad180000000p-3f, -0x1.d8610a0000000p-2f, 0x1.57d9240000000p+0f, -0x1.8cbbc80000000p-2f, -0x1.6a67480000000p-1f, 0x1.8d0d9a0000000p-2f, -0x1.0630440000000p-3f, 0x1.b1ab620000000p-2f, 0x1.9947ce0000000p-2f, 0x1.a1de1a0000000p-4f, 0x1.6be6a80000000p+0f, 0x1.67745c0000000p+0f, -0x1.0f15b40000000p-2f, -0x1.0892440000000p-1f, 0x1.112b600000000p-4f, 0x1.b3f71c0000000p+0f, -0x1.58b4ae0000000p+0f, -0x1.9221740000000p-1f, 0x1.99676c0000000p+0f, 0x1.e6f7260000000p+0f, 0x1.c986800000000p-1f, -0x1.b1022c0000000p-6f, -0x1.aea5ac0000000p-1f, -0x1.718d000000000p-1f, 0x1.64e4680000000p+0f, -0x1.4871160000000p-6f, 0x1.bb0d760000000p-3f, -0x1.6cd4d40000000p-4f, 0x1.c197780000000p-1f, -0x1.11eefe0000000p+1f, 0x1.b3f9e20000000p-1f, -0x1.daa97a0000000p-3f, 0x1.f08fc20000000p-2f, 0x1.10453c0000000p+0f, 0x1.a3b2c20000000p-1f };
__global float A_data_1[64] = { -0x1.a71ac80000000p+0f, -0x1.04cc9c0000000p+0f, 0x1.f4c60c0000000p-1f, 0x1.e34d960000000p-1f, -0x1.9a4d920000000p+0f, -0x1.7fa4e80000000p-1f, 0x1.9c2dac0000000p-1f, 0x1.2c1b380000000p-1f, 0x1.b06c5e0000000p-2f, -0x1.0ce4b80000000p-3f, -0x1.7f659c0000000p+0f, 0x1.e1e1460000000p-1f, -0x1.ed1d620000000p-5f, 0x1.4547de0000000p-3f, -0x1.292dee0000000p-7f, -0x1.1406420000000p+0f, -0x1.ca65980000000p-1f, 0x1.bdbc760000000p-2f, 0x1.4d13680000000p-4f, 0x1.248ba80000000p+0f, -0x1.3198380000000p-1f, -0x1.d20c220000000p-2f, -0x1.1e733c0000000p+0f, -0x1.518b0e0000000p-8f, 0x1.350c140000000p+0f, -0x1.07a5f20000000p+0f, -0x1.2bed820000000p+0f, -0x1.e659f40000000p-3f, -0x1.7889100000000p-1f, -0x1.0646a80000000p+0f, -0x1.4d8f220000000p+0f, 0x1.bb9f9a0000000p+0f, -0x1.7e70060000000p+0f, 0x1.26ea240000000p+0f, -0x1.b48a2a0000000p-1f, 0x1.12804c0000000p-1f, 0x1.e84ac40000000p-2f, -0x1.5529aa0000000p+0f, -0x1.3c1a280000000p-1f, -0x1.ab63460000000p-3f, -0x1.06460e0000000p-1f, -0x1.7a98740000000p-1f, -0x1.ed2f720000000p+0f, 0x1.50ea2a0000000p+0f, 0x1.c867080000000p-1f, 0x1.9ddd8c0000000p-1f, 0x1.828a660000000p-2f, -0x1.ae73a60000000p-4f, 0x1.74254a0000000p-2f, -0x1.4f95d00000000p+0f, 0x1.de3c9a0000000p-3f, -0x1.3ae1c60000000p-4f, 0x1.3dbd060000000p-2f, 0x1.babee40000000p+0f, 0x1.e94ac60000000p-4f, 0x1.c406b20000000p-2f, 0x1.9050e20000000p+0f, 0x1.20b1c20000000p+0f, -0x1.1b2a800000000p+0f, -0x1.2313740000000p-1f, -0x1.d591b40000000p-1f, -0x1.7aefc80000000p-1f, -0x1.7aa0660000000p+0f, 0x1.8da04a0000000p-1f };
__global float T_add_0[64] = { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f };
__global float EXP_data[N] = { -0x1.9605400000000p+0f, -0x1.0040880000000p-1f, 0x1.55b2340000000p-1f, -0x1.c500720000000p-1f, -0x1.6f01380000000p+0f, -0x1.c799be0000000p-2f, -0x1.862e380000000p-2f, -0x1.09946a0000000p+0f, 0x1.0c114c0000000p+0f, -0x1.4adc3c0000000p+0f, -0x1.9c49140000000p-1f, 0x1.0665000000000p+0f, -0x1.1c93c20000000p-2f, -0x1.13eca60000000p-3f, 0x1.3fccc40000000p-2f, -0x1.388aee0000000p+1f, -0x1.7367860000000p-1f, 0x1.392a1c0000000p-3f, -0x1.f5c4820000000p+0f, -0x1.cf80000000000p-1f, 0x1.85c3780000000p-1f, 0x1.7de5fe0000000p+0f, -0x1.01c31e0000000p+0f, -0x1.00b5600000000p-3f, -0x1.b878100000000p-3f, -0x1.d532880000000p+0f, -0x1.2b04020000000p+0f, 0x1.0f21800000000p-5f, -0x1.aec3fc0000000p+0f, -0x1.baa20a0000000p-1f, -0x1.c3a7640000000p+0f, 0x1.89bc600000000p+1f, -0x1.e19ef80000000p+0f, 0x1.c6da000000000p-2f, -0x1.dc06ba0000000p-2f, 0x1.a1e8760000000p-2f, 0x1.ccfb140000000p-1f, -0x1.ddaf6c0000000p-1f, -0x1.07de640000000p-1f, 0x1.367a400000000p+0f, 0x1.c8a2aa0000000p-1f, -0x1.0111a80000000p+0f, -0x1.38bc4a0000000p+1f, 0x1.61fce00000000p+0f, 0x1.4c15500000000p+1f, -0x1.138bd00000000p-1f, -0x1.a1b8820000000p-2f, 0x1.7e80320000000p+0f, 0x1.22003c0000000p+1f, -0x1.ab4a400000000p-2f, 0x1.a81c540000000p-3f, -0x1.d601e40000000p-1f, -0x1.a55cfa0000000p-2f, 0x1.8fd1a60000000p+1f, 0x1.972e800000000p-4f, 0x1.50c6b60000000p-1f, 0x1.7983940000000p+0f, 0x1.00bec00000000p+1f, -0x1.9f843e0000000p+1f, 0x1.21ccdc0000000p-2f, -0x1.261e0a0000000p+0f, -0x1.054fce0000000p-2f, -0x1.a96ca80000000p-2f, 0x1.98a9860000000p+0f };
__global volatile uint32_t mismatch_flag = 0u;

int main() {
  {
    compgen_pack_add_0_args a = { A_data_0, A_data_1, T_add_0 };
    mu_schedule(compgen_pack_add_0_callback, &a, 4);
  }
  {
    compgen_pack_verify_args a = { T_add_0, EXP_data, &mismatch_flag };
    mu_schedule(compgen_pack_verify_kernel, &a, 1);
  }
  return 0;
}
