#!/usr/bin/env python3
"""Generate `data` for the Gemma-2 decoder-layer 4-norm/residual "sandwich" kernel.

Replicates the exact ordering the kernel computes (self_attn/mlp are STUBBED as
per-channel transforms *wa / *wm, since those ops are covered by their own kernels):

  inv = rsqrt(mean(x^2)+eps);   tmp = x*inv*(1+w_in) * wa                 # NORM1 + attn stub
  inv = rsqrt(mean(tmp^2)+eps); out = x   + tmp*inv*(1+w_pa)              # NORM2 + RESIDUAL1
  inv = rsqrt(mean(out^2)+eps); tmp = out*inv*(1+w_pf) * wm               # NORM3 + mlp stub
  inv = rsqrt(mean(tmp^2)+eps); out = out + tmp*inv*(1+w_pff)             # NORM4 + RESIDUAL2

Each norm is Gemma2RMSNorm (rms * (1.0 + weight)), eps=1e-6. fp32, ROWS=8 x COLS=2304.
Golden is numpy fp32 with the same op; the kernel verifies with an FP tolerance. Emit
helpers come from the shared golden module (lib/golden).
"""
import pathlib
import sys

import numpy as np

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parents[2] / "lib" / "golden"))
import golden as G

HERE = pathlib.Path(__file__).resolve().parent
ROWS, COLS, EPS = 8, 2304, 1.0e-6


def inv_rms(row):
    return (1.0 / np.sqrt((row ** 2).mean(axis=1, keepdims=True) + EPS)).astype(np.float32)


def main():
    rng = np.random.default_rng(0x4E074)
    x = rng.standard_normal((ROWS, COLS)).astype(np.float32)
    w_in = (0.1 * rng.standard_normal(COLS)).astype(np.float32)
    w_pa = (0.1 * rng.standard_normal(COLS)).astype(np.float32)
    w_pf = (0.1 * rng.standard_normal(COLS)).astype(np.float32)
    w_pff = (0.1 * rng.standard_normal(COLS)).astype(np.float32)
    wa = (1.0 + 0.1 * rng.standard_normal(COLS)).astype(np.float32)  # attn stub (per-channel)
    wm = (1.0 + 0.1 * rng.standard_normal(COLS)).astype(np.float32)  # mlp stub (per-channel)

    tmp = (x * inv_rms(x) * (1.0 + w_in)[None, :] * wa[None, :]).astype(np.float32)
    out = (x + tmp * inv_rms(tmp) * (1.0 + w_pa)[None, :]).astype(np.float32)
    tmp = (out * inv_rms(out) * (1.0 + w_pf)[None, :] * wm[None, :]).astype(np.float32)
    gold = (out + tmp * inv_rms(tmp) * (1.0 + w_pff)[None, :]).astype(np.float32)

    z = np.zeros(ROWS * COLS, np.float32)
    with open(HERE / "data", "w") as f:
        f.write("// @generated by gen_data.py -- Gemma-2 decoder-layer 4-norm/residual sandwich\n")
        f.write("#include <stdint.h>\n")
        f.write(f"#define VERIFY_COUNT {ROWS * COLS}\n")
        f.write(f"static const uint32_t ROWS = {ROWS};\nstatic const uint32_t COLS = {COLS};\n")
        G.emit_f32(f, "x_raw", x, dims=f"[{ROWS * COLS}]", ncol=8)
        for name, w in [("w_in_raw", w_in), ("w_pa_raw", w_pa), ("w_pf_raw", w_pf),
                        ("w_pff_raw", w_pff), ("wa_raw", wa), ("wm_raw", wm)]:
            G.emit_f32(f, name, w, dims=f"[{COLS}]", ncol=8)
        G.emit_f32(f, "tmp_raw", z, dims=f"[{ROWS * COLS}]", ncol=8)
        G.emit_f32(f, "out_raw", z, dims=f"[{ROWS * COLS}]", ncol=8)
        G.emit_f32(f, "gold_raw", gold, dims=f"[{ROWS * COLS}]", ncol=8)
        G.emit_f32(f, "tls_guard", np.zeros(1024, np.float32), dims="[1024]", ncol=8)
    print(f"wrote gemma_4norm data ROWS={ROWS} COLS={COLS}")


if __name__ == "__main__":
    main()
