// Auto-composed by radiance_muon._bundle_kernel from CompGen's
// bundle/generated_kernels/* + payload.mlir + execution_plan.yaml +
// golden_inputs.pt + golden_outputs.pt.
//
// Per-region compute callbacks come from the
// radiance_muon_elementwise provider verbatim. The pack contributes
// data baking, dispatch sequencing, and verification.
#include <mu_intrinsics.h>
#include <mu_schedule.h>
#include <stdint.h>

#define N 4

// ========== region matmul_0 (op=linalg.matmul) ==========
// Auto-generated by RadianceMuonMatmulProvider.
// region_id = matmul_0
// op_family = matmul
// M         = 2
// K         = 2
// N         = 2
//
// Compute-only emit. The pack's composer wraps this with includes,
// data arrays (M*K + K*N flat float32 init), an MxN output buffer,
// dispatch sequencing, and verification against the model's golden.

struct compgen_region_matmul_0_args {
  __global float* A;   // M*K row-major
  __global float* B;   // K*N row-major
  __global float* C;   // M*N row-major
};

static inline void compgen_region_matmul_0_compute(
    void* arg, uint32_t tid, uint32_t /*nthreads*/, uint32_t /*blk*/) {
  if (tid != 0) return;
  auto* a = reinterpret_cast<compgen_region_matmul_0_args*>(arg);
  for (uint32_t m = 0; m < 2; ++m) {
    for (uint32_t n = 0; n < 2; ++n) {
      float acc = 0.0f;
      for (uint32_t k = 0; k < 2; ++k) {
        acc += a->A[m * 2 + k] * a->B[k * 2 + n];
      }
      a->C[m * 2 + n] = acc;
    }
  }
}

struct compgen_pack_matmul_0_args {
  __global float* A;
  __global float* B;
  __global float* C;
};

static void compgen_pack_matmul_0_callback(
    void* arg, uint32_t tid, uint32_t nthreads, uint32_t blk) {
  auto* a = reinterpret_cast<compgen_pack_matmul_0_args*>(arg);
  compgen_region_matmul_0_args inner = { a->A, a->B, a->C };
  compgen_region_matmul_0_compute(&inner, tid, nthreads, blk);
}

struct compgen_pack_verify_args {
  __global float* C;
  __global float* EXP;
  __global volatile uint32_t* mismatch;
};

static void compgen_pack_verify_kernel(
    void* arg, uint32_t tid, uint32_t /*nthreads*/, uint32_t /*blk*/) {
  auto* a = reinterpret_cast<compgen_pack_verify_args*>(arg);
  if (tid != 0) return;
  // Accumulate any-mismatch via XOR-OR rather than per-iteration
  // ``if`` checks — at moderate N (≥32) the per-iteration branch
  // form pushes onto Muon's ipdom (immediate post-dominator) stack
  // without timely pops and the sim asserts ``ipdom stack is full``.
  // Branch-free accumulation keeps the loop body straight-line.
  uint32_t mismatch_bits = 0u;
  for (uint32_t i = 0; i < 4; ++i) {
    uint32_t got = __builtin_bit_cast(uint32_t, a->C[i]);
    uint32_t exp = __builtin_bit_cast(uint32_t, a->EXP[i]);
    mismatch_bits |= (got ^ exp);
  }
  if (mismatch_bits != 0u) {
    *a->mismatch = 0xDEADBEEFu;
    for (;;) { /* never go idle — sim cycle-budget will fire */ }
  }
}

__global float A_data_0[4] = { -0x1.2ca2e80000000p-3f, 0x1.92811c0000000p-1f, 0x1.e4c5ce0000000p-1f, -0x1.1d45a60000000p+0f };
__global float A_data_1[4] = { 0x1.b0d7a00000000p+0f, -0x1.ca26e20000000p-1f, -0x1.6c28f80000000p-2f, 0x1.3b7da20000000p+0f };
__global float T_matmul_0[4] = { 0.0f, 0.0f, 0.0f, 0.0f };
__global float EXP_data[N] = { -0x1.0e38080000000p-1f, 0x1.19a5c40000000p+0f, 0x1.ff463a0000000p+0f, -0x1.1c3aca0000000p+1f };
__global volatile uint32_t mismatch_flag = 0u;

int main() {
  {
    compgen_pack_matmul_0_args a = { A_data_0, A_data_1, T_matmul_0 };
    mu_schedule(compgen_pack_matmul_0_callback, &a, 1);
  }
  {
    compgen_pack_verify_args a = { T_matmul_0, EXP_data, &mismatch_flag };
    mu_schedule(compgen_pack_verify_kernel, &a, 1);
  }
  return 0;
}
